const hiragana_dasar = [
    { char: 'あ', romaji: 'a', strokes: 'Mulai dari kiri ke kanan, kemudian dari atas ke bawah' },
    { char: 'い', romaji: 'i', strokes: 'Dua garis vertikal dari atas ke bawah' },
    { char: 'う', romaji: 'u', strokes: 'Garis horizontal, lalu lengkungan dari kiri bawah' },
    { char: 'え', romaji: 'e', strokes: 'Garis horizontal atas, lalu vertikal, lalu horizontal bawah' },
    { char: 'お', romaji: 'o', strokes: 'Dari atas kiri melengkung ke bawah dan kanan' },
    { char: 'か', romaji: 'ka', strokes: 'Tiga goresan: horizontal, vertikal, diagonal' },
    { char: 'き', romaji: 'ki', strokes: 'Tiga garis horizontal, satu garis vertikal' },
    { char: 'く', romaji: 'ku', strokes: 'Satu goresan melengkung dari atas ke bawah kanan' },
    { char: 'け', romaji: 'ke', strokes: 'Tiga goresan: diagonal, horizontal, vertikal' },
    { char: 'こ', romaji: 'ko', strokes: 'Dua garis horizontal' },
    { char: 'さ', romaji: 'sa', strokes: 'Tiga goresan: horizontal, vertikal melengkung, horizontal' },
    { char: 'し', romaji: 'shi', strokes: 'Satu goresan lengkungan dari atas ke bawah' },
    { char: 'す', romaji: 'su', strokes: 'Dua goresan melengkung' },
    { char: 'せ', romaji: 'se', strokes: 'Tiga goresan: horizontal, lengkungan, horizontal' },
    { char: 'そ', romaji: 'so', strokes: 'Dua goresan: horizontal melengkung, lengkungan besar' },
    { char: 'た', romaji: 'ta', strokes: 'Tiga goresan: horizontal, vertikal, lengkungan' },
    { char: 'ち', romaji: 'chi', strokes: 'Dua goresan: horizontal, lengkungan panjang' },
    { char: 'つ', romaji: 'tsu', strokes: 'Satu goresan melengkung horizontal' },
    { char: 'て', romaji: 'te', strokes: 'Satu goresan horizontal dengan ekor ke bawah' },
    { char: 'と', romaji: 'to', strokes: 'Dua goresan: vertikal, lengkungan' },
    { char: 'な', romaji: 'na', strokes: 'Empat goresan dari kiri ke kanan' },
    { char: 'に', romaji: 'ni', strokes: 'Tiga goresan: horizontal, horizontal, vertikal' },
    { char: 'ぬ', romaji: 'nu', strokes: 'Dua goresan melengkung dengan lingkaran' },
    { char: 'ね', romaji: 'ne', strokes: 'Tiga goresan dengan lengkungan besar' },
    { char: 'の', romaji: 'no', strokes: 'Satu goresan spiral' },
    { char: 'は', romaji: 'ha', strokes: 'Tiga goresan: vertikal, lengkungan, lingkaran' },
    { char: 'ひ', romaji: 'hi', strokes: 'Dua goresan: vertikal, horizontal dengan lengkungan' },
    { char: 'ふ', romaji: 'fu', strokes: 'Empat goresan membentuk huruf' },
    { char: 'へ', romaji: 'he', strokes: 'Satu goresan diagonal dari kiri atas ke kanan bawah' },
    { char: 'ほ', romaji: 'ho', strokes: 'Empat goresan: horizontal, vertikal, dua lengkungan' },
    { char: 'ま', romaji: 'ma', strokes: 'Tiga goresan: horizontal, vertikal, lengkungan' },
    { char: 'み', romaji: 'mi', strokes: 'Dua goresan melengkung' },
    { char: 'む', romaji: 'mu', strokes: 'Tiga goresan dengan lengkungan besar' },
    { char: 'め', romaji: 'me', strokes: 'Dua goresan membentuk angka 8' },
    { char: 'も', romaji: 'mo', strokes: 'Tiga goresan: horizontal, vertikal, lengkungan' },
    { char: 'や', romaji: 'ya', strokes: 'Tiga goresan membentuk huruf' },
    { char: 'ゆ', romaji: 'yu', strokes: 'Dua goresan melengkung' },
    { char: 'よ', romaji: 'yo', strokes: 'Dua goresan: horizontal, vertikal melengkung' },
    { char: 'ら', romaji: 'ra', strokes: 'Dua goresan: vertikal dengan lengkungan' },
    { char: 'り', romaji: 'ri', strokes: 'Dua goresan: vertikal, horizontal dengan lengkungan' },
    { char: 'る', romaji: 'ru', strokes: 'Dua goresan membentuk spiral kecil' },
    { char: 'れ', romaji: 're', strokes: 'Satu goresan melengkung dengan ekor' },
    { char: 'ろ', romaji: 'ro', strokes: 'Tiga goresan: horizontal, vertikal, lengkungan' },
    { char: 'わ', romaji: 'wa', strokes: 'Dua goresan melengkung' },
    { char: 'を', romaji: 'wo', strokes: 'Tiga goresan: horizontal, lengkungan, vertikal' },
    { char: 'ん', romaji: 'n', strokes: 'Satu goresan melengkung seperti gelombang' }
];

const hiragana_dakuten = [
    { char: 'が', romaji: 'ga' }, { char: 'ぎ', romaji: 'gi' }, { char: 'ぐ', romaji: 'gu' },
    { char: 'げ', romaji: 'ge' }, { char: 'ご', romaji: 'go' },
    { char: 'ざ', romaji: 'za' }, { char: 'じ', romaji: 'ji' }, { char: 'ず', romaji: 'zu' },
    { char: 'ぜ', romaji: 'ze' }, { char: 'ぞ', romaji: 'zo' },
    { char: 'だ', romaji: 'da' }, { char: 'ぢ', romaji: 'ji' }, { char: 'づ', romaji: 'zu' },
    { char: 'で', romaji: 'de' }, { char: 'ど', romaji: 'do' },
    { char: 'ば', romaji: 'ba' }, { char: 'び', romaji: 'bi' }, { char: 'ぶ', romaji: 'bu' },
    { char: 'べ', romaji: 'be' }, { char: 'ぼ', romaji: 'bo' }
];

const hiragana_handakuten = [
    { char: 'ぱ', romaji: 'pa' }, { char: 'ぴ', romaji: 'pi' }, { char: 'ぷ', romaji: 'pu' },
    { char: 'ぺ', romaji: 'pe' }, { char: 'ぽ', romaji: 'po' }
];

const hiragana_youon = [
    { char: 'きゃ', romaji: 'kya' }, { char: 'きゅ', romaji: 'kyu' }, { char: 'きょ', romaji: 'kyo' },
    { char: 'しゃ', romaji: 'sha' }, { char: 'しゅ', romaji: 'shu' }, { char: 'しょ', romaji: 'sho' },
    { char: 'ちゃ', romaji: 'cha' }, { char: 'ちゅ', romaji: 'chu' }, { char: 'ちょ', romaji: 'cho' },
    { char: 'にゃ', romaji: 'nya' }, { char: 'にゅ', romaji: 'nyu' }, { char: 'にょ', romaji: 'nyo' },
    { char: 'ひゃ', romaji: 'hya' }, { char: 'ひゅ', romaji: 'hyu' }, { char: 'ひょ', romaji: 'hyo' },
    { char: 'みゃ', romaji: 'mya' }, { char: 'みゅ', romaji: 'myu' }, { char: 'みょ', romaji: 'myo' },
    { char: 'りゃ', romaji: 'rya' }, { char: 'りゅ', romaji: 'ryu' }, { char: 'りょ', romaji: 'ryo' },
    { char: 'ぎゃ', romaji: 'gya' }, { char: 'ぎゅ', romaji: 'gyu' }, { char: 'ぎょ', romaji: 'gyo' },
    { char: 'じゃ', romaji: 'ja' }, { char: 'じゅ', romaji: 'ju' }, { char: 'じょ', romaji: 'jo' },
    { char: 'ぢゃ', romaji: 'ja' }, { char: 'ぢゅ', romaji: 'ju' }, { char: 'ぢょ', romaji: 'jo' },
    { char: 'びゃ', romaji: 'bya' }, { char: 'びゅ', romaji: 'byu' }, { char: 'びょ', romaji: 'byo' },
    { char: 'ぴゃ', romaji: 'pya' }, { char: 'ぴゅ', romaji: 'pyu' }, { char: 'ぴょ', romaji: 'pyo' }
];

const katakana_dasar = [
    { char: 'ア', romaji: 'a', strokes: 'Dua goresan diagonal dari atas' },
    { char: 'イ', romaji: 'i', strokes: 'Dua garis vertikal' },
    { char: 'ウ', romaji: 'u', strokes: 'Tiga goresan membentuk huruf' },
    { char: 'エ', romaji: 'e', strokes: 'Tiga garis horizontal' },
    { char: 'オ', romaji: 'o', strokes: 'Tiga goresan: horizontal, vertikal, diagonal' },
    { char: 'カ', romaji: 'ka', strokes: 'Dua goresan: horizontal, diagonal' },
    { char: 'キ', romaji: 'ki', strokes: 'Tiga garis horizontal, satu vertikal' },
    { char: 'ク', romaji: 'ku', strokes: 'Dua garis diagonal' },
    { char: 'ケ', romaji: 'ke', strokes: 'Tiga goresan membentuk sudut' },
    { char: 'コ', romaji: 'ko', strokes: 'Dua garis horizontal' },
    { char: 'サ', romaji: 'sa', strokes: 'Tiga goresan: horizontal, vertikal, diagonal' },
    { char: 'シ', romaji: 'shi', strokes: 'Tiga garis diagonal pendek' },
    { char: 'ス', romaji: 'su', strokes: 'Dua goresan diagonal' },
    { char: 'セ', romaji: 'se', strokes: 'Dua garis horizontal, satu diagonal' },
    { char: 'ソ', romaji: 'so', strokes: 'Dua garis diagonal pendek' },
    { char: 'タ', romaji: 'ta', strokes: 'Tiga goresan: horizontal, vertikal, diagonal' },
    { char: 'チ', romaji: 'chi', strokes: 'Tiga goresan membentuk huruf' },
    { char: 'ツ', romaji: 'tsu', strokes: 'Tiga garis diagonal vertikal' },
    { char: 'テ', romaji: 'te', strokes: 'Tiga goresan: horizontal, vertikal, horizontal' },
    { char: 'ト', romaji: 'to', strokes: 'Dua goresan: vertikal, diagonal' },
    { char: 'ナ', romaji: 'na', strokes: 'Dua goresan: horizontal diagonal, vertikal' },
    { char: 'ニ', romaji: 'ni', strokes: 'Dua garis horizontal' },
    { char: 'ヌ', romaji: 'nu', strokes: 'Dua goresan: diagonal, lengkungan' },
    { char: 'ネ', romaji: 'ne', strokes: 'Empat goresan membentuk huruf' },
    { char: 'ノ', romaji: 'no', strokes: 'Satu garis diagonal dari kiri atas ke kanan bawah' },
    { char: 'ハ', romaji: 'ha', strokes: 'Dua garis diagonal ke kanan' },
    { char: 'ヒ', romaji: 'hi', strokes: 'Dua goresan: vertikal, horizontal' },
    { char: 'フ', romaji: 'fu', strokes: 'Dua goresan: horizontal, diagonal' },
    { char: 'ヘ', romaji: 'he', strokes: 'Satu garis diagonal seperti topi' },
    { char: 'ホ', romaji: 'ho', strokes: 'Empat goresan membentuk kotak' },
    { char: 'マ', romaji: 'ma', strokes: 'Dua goresan: horizontal, vertikal diagonal' },
    { char: 'ミ', romaji: 'mi', strokes: 'Tiga garis horizontal pendek' },
    { char: 'ム', romaji: 'mu', strokes: 'Dua goresan diagonal membentuk V' },
    { char: 'メ', romaji: 'me', strokes: 'Dua garis diagonal menyilang' },
    { char: 'モ', romaji: 'mo', strokes: 'Tiga goresan: horizontal, vertikal, horizontal' },
    { char: 'ヤ', romaji: 'ya', strokes: 'Tiga goresan membentuk huruf' },
    { char: 'ユ', romaji: 'yu', strokes: 'Dua goresan: horizontal, lengkungan' },
    { char: 'ヨ', romaji: 'yo', strokes: 'Tiga garis horizontal' },
    { char: 'ラ', romaji: 'ra', strokes: 'Dua goresan: vertikal, horizontal' },
    { char: 'リ', romaji: 'ri', strokes: 'Dua garis vertikal' },
    { char: 'ル', romaji: 'ru', strokes: 'Dua goresan: vertikal, lengkungan' },
    { char: 'レ', romaji: 're', strokes: 'Dua goresan membentuk L' },
    { char: 'ロ', romaji: 'ro', strokes: 'Tiga goresan membentuk kotak' },
    { char: 'ワ', romaji: 'wa', strokes: 'Dua goresan: horizontal diagonal, vertikal' },
    { char: 'ヲ', romaji: 'wo', strokes: 'Tiga goresan membentuk huruf' },
    { char: 'ン', romaji: 'n', strokes: 'Satu garis diagonal dengan ekor' }
];

const katakana_dakuten = [
    { char: 'ガ', romaji: 'ga' }, { char: 'ギ', romaji: 'gi' }, { char: 'グ', romaji: 'gu' },
    { char: 'ゲ', romaji: 'ge' }, { char: 'ゴ', romaji: 'go' },
    { char: 'ザ', romaji: 'za' }, { char: 'ジ', romaji: 'ji' }, { char: 'ズ', romaji: 'zu' },
    { char: 'ゼ', romaji: 'ze' }, { char: 'ゾ', romaji: 'zo' },
    { char: 'ダ', romaji: 'da' }, { char: 'ヂ', romaji: 'ji' }, { char: 'ヅ', romaji: 'zu' },
    { char: 'デ', romaji: 'de' }, { char: 'ド', romaji: 'do' },
    { char: 'バ', romaji: 'ba' }, { char: 'ビ', romaji: 'bi' }, { char: 'ブ', romaji: 'bu' },
    { char: 'ベ', romaji: 'be' }, { char: 'ボ', romaji: 'bo' }
];

const katakana_handakuten = [
    { char: 'パ', romaji: 'pa' }, { char: 'ピ', romaji: 'pi' }, { char: 'プ', romaji: 'pu' },
    { char: 'ペ', romaji: 'pe' }, { char: 'ポ', romaji: 'po' }
];

const katakana_youon = [
    { char: 'キャ', romaji: 'kya' }, { char: 'キュ', romaji: 'kyu' }, { char: 'キョ', romaji: 'kyo' },
    { char: 'シャ', romaji: 'sha' }, { char: 'シュ', romaji: 'shu' }, { char: 'ショ', romaji: 'sho' },
    { char: 'チャ', romaji: 'cha' }, { char: 'チュ', romaji: 'chu' }, { char: 'チョ', romaji: 'cho' },
    { char: 'ニャ', romaji: 'nya' }, { char: 'ニュ', romaji: 'nyu' }, { char: 'ニョ', romaji: 'nyo' },
    { char: 'ヒャ', romaji: 'hya' }, { char: 'ヒュ', romaji: 'hyu' }, { char: 'ヒョ', romaji: 'hyo' },
    { char: 'ミャ', romaji: 'mya' }, { char: 'ミュ', romaji: 'myu' }, { char: 'ミョ', romaji: 'myo' },
    { char: 'リャ', romaji: 'rya' }, { char: 'リュ', romaji: 'ryu' }, { char: 'リョ', romaji: 'ryo' },
    { char: 'ギャ', romaji: 'gya' }, { char: 'ギュ', romaji: 'gyu' }, { char: 'ギョ', romaji: 'gyo' },
    { char: 'ジャ', romaji: 'ja' }, { char: 'ジュ', romaji: 'ju' }, { char: 'ジョ', romaji: 'jo' },
    { char: 'ヂャ', romaji: 'ja' }, { char: 'ヂュ', romaji: 'ju' }, { char: 'ヂョ', romaji: 'jo' },
    { char: 'ビャ', romaji: 'bya' }, { char: 'ビュ', romaji: 'byu' }, { char: 'ビョ', romaji: 'byo' },
    { char: 'ピャ', romaji: 'pya' }, { char: 'ピュ', romaji: 'pyu' }, { char: 'ピョ', romaji: 'pyo' }
];

const katakana_modern = [
    { char: 'ウィ', romaji: 'wi' }, { char: 'ウェ', romaji: 'we' }, { char: 'ウォ', romaji: 'wo' },
    { char: 'ヴァ', romaji: 'va' }, { char: 'ヴィ', romaji: 'vi' }, { char: 'ヴ', romaji: 'vu' },
    { char: 'ヴェ', romaji: 've' }, { char: 'ヴォ', romaji: 'vo' },
    { char: 'ファ', romaji: 'fa' }, { char: 'フィ', romaji: 'fi' }, { char: 'フェ', romaji: 'fe' },
    { char: 'フォ', romaji: 'fo' }, { char: 'フュ', romaji: 'fyu' },
    { char: 'ツァ', romaji: 'tsa' }, { char: 'ツィ', romaji: 'tsi' }, { char: 'ツェ', romaji: 'tse' },
    { char: 'ツォ', romaji: 'tso' },
    { char: 'ティ', romaji: 'ti' }, { char: 'トゥ', romaji: 'tu' },
    { char: 'ディ', romaji: 'di' }, { char: 'ドゥ', romaji: 'du' }, { char: 'デュ', romaji: 'dyu' },
    { char: 'チェ', romaji: 'che' }, { char: 'シェ', romaji: 'she' }, { char: 'ジェ', romaji: 'je' }
];

const kotoba = [
    { jp: 'おはようございます', romaji: 'ohayou gozaimasu', meaning: 'Selamat Pagi', category: 'greetings' },
    { jp: 'こんにちは', romaji: 'konnichiwa', meaning: 'Selamat Siang', category: 'greetings' },
    { jp: 'こんばんは', romaji: 'konbanwa', meaning: 'Selamat Malam', category: 'greetings' },
    { jp: 'おやすみなさい', romaji: 'oyasuminasai', meaning: 'Selamat Tidur', category: 'greetings' },
    { jp: 'いらっしゃいませ', romaji: 'irasshaimase', meaning: 'Selamat Datang', category: 'greetings' },
    { jp: 'さようなら', romaji: 'sayounara', meaning: 'Selamat Tinggal', category: 'greetings' },
    { jp: 'ただいま', romaji: 'tadaima', meaning: 'Aku Kembali (Rumah)', category: 'greetings' },
    { jp: 'おかえりなさい', romaji: 'okaerinasai', meaning: 'Selamat Datang Kembali', category: 'greetings' },
    { jp: 'いってきます', romaji: 'ittekimasu', meaning: 'Aku Pamit', category: 'greetings' },
    { jp: 'いってらっしゃい', romaji: 'itterasshai', meaning: 'Hati-hati', category: 'greetings' },
    { jp: 'またね', romaji: 'matane', meaning: 'Sampai Jumpa', category: 'greetings' },
    { jp: 'げんきです', romaji: 'genki desu', meaning: 'Kabar baik', category: 'greetings' },
    { jp: 'おめでとう', romaji: 'omedetou', meaning: 'Selamat', category: 'greetings' },
    { jp: 'おひさしぶりです', romaji: 'ohisashiburi desu', meaning: 'Sudah lama tidak bertemu', category: 'greetings' },
    { jp: 'おまたせしました', romaji: 'omatase shimashita', meaning: 'Maaf lama menunggu', category: 'greetings' },
    { jp: 'おねがいします', romaji: 'onegaishimasu', meaning: 'Mohon bantuannya', category: 'greetings' },
    { jp: 'すみません', romaji: 'sumimasen', meaning: 'Permisi / Maaf', category: 'greetings' },
    { jp: 'やめて', romaji: 'yamete', meaning: 'Berhenti', category: 'greetings' },
    { jp: 'すごい', romaji: 'sugoi', meaning: 'Hebat / Luar biasa', category: 'greetings' },
    { jp: 'かっこいい', romaji: 'kakkoii', meaning: 'Keren', category: 'greetings' },
    { jp: 'しつれいします', romaji: 'shitsureishimasu', meaning: 'Permisi', category: 'greetings' },
    { jp: 'ごめん', romaji: 'gomen', meaning: 'Maaf', category: 'greetings' },
    { jp: 'だいじょうぶ', romaji: 'daijoubu', meaning: 'Tidak apa apa', category: 'greetings' },
    { jp: 'ありがとう', romaji: 'arigatou', meaning: 'Terima kasih', category: 'greetings' },
    { jp: 'どういたしまして', romaji: 'douitashimashite', meaning: 'Sama-sama', category: 'greetings' },
    { jp: 'ちょっとまって', romaji: 'chotto matte', meaning: 'Tunggu sebentar', category: 'greetings' },
    { jp: 'おつかれさまです', romaji: 'otsukaresama desu', meaning: 'Terimakasih atas kerja kerasnya', category: 'greetings' },
    { jp: 'はじめまして', romaji: 'hajimemashite', meaning: 'Salam kenal', category: 'greetings' },
    { jp: 'どうぞよろしく', romaji: 'douzo yoroshiku', meaning: 'Mohon bantuannya (kenalan)', category: 'greetings' },
    { jp: 'おげんきですか', romaji: 'ogenki desu ka', meaning: 'Apa kabar', category: 'greetings' },
    { jp: 'わかりました', romaji: 'wakarimashita', meaning: 'Mengerti / Paham', category: 'greetings' },
    { jp: 'わかりません', romaji: 'wakarimasen', meaning: 'Tidak mengerti', category: 'greetings' },
    { jp: 'しりません', romaji: 'shirimasen', meaning: 'Tidak tahu', category: 'greetings' },
    { jp: 'がんばって', romaji: 'ganbatte', meaning: 'Semangat', category: 'greetings' },
    { jp: 'だいすき', romaji: 'daisuki', meaning: 'Sangat suka', category: 'greetings' },
    { jp: 'もちろん', romaji: 'mochiron', meaning: 'Tentu saja', category: 'greetings' },
    { jp: 'ほんとうですか', romaji: 'hontou desu ka', meaning: 'Benarkah', category: 'greetings' },
    { jp: 'そうですね', romaji: 'sou desu ne', meaning: 'Begitu ya', category: 'greetings' },
    { jp: 'いいですよ', romaji: 'ii desu yo', meaning: 'Boleh / Oke', category: 'greetings' },
    { jp: 'だめです', romaji: 'dame desu', meaning: 'Tidak boleh', category: 'greetings' },
    { jp: 'けっこうです', romaji: 'kekkou desu', meaning: 'Tidak usah / Cukup', category: 'greetings' },
    { jp: 'おだいじに', romaji: 'odaijini', meaning: 'Semoga cepat sembuh', category: 'greetings' },
    { jp: 'きをつけて', romaji: 'ki wo tsukete', meaning: 'Hati-hati', category: 'greetings' },
    { jp: 'いただきます', romaji: 'itadakimasu', meaning: 'Selamat makan (sebelum)', category: 'greetings' },
    { jp: 'ごちそうさまでした', romaji: 'gochisousama deshita', meaning: 'Terima kasih atas hidangannya', category: 'greetings' },
    { jp: 'しつれいしました', romaji: 'shitsurei shimashita', meaning: 'Permisi (setelah)', category: 'greetings' },
    { jp: 'もしもし', romaji: 'moshi moshi', meaning: 'Halo (telepon)', category: 'greetings' },
    { jp: 'おきをつけて', romaji: 'oki wo tsukete', meaning: 'Hati-hati di jalan', category: 'greetings' },
    { jp: 'そうですか', romaji: 'sou desu ka', meaning: 'Oh begitu', category: 'greetings' },
    { jp: 'ちがいます', romaji: 'chigaimasu', meaning: 'Bukan / Salah', category: 'greetings' },
    { jp: 'わたし', romaji: 'watashi', meaning: 'Saya', category: 'basic' },
    { jp: 'ぼく', romaji: 'boku', meaning: 'Saya (laki-laki)', category: 'basic' },
    { jp: 'かれら', romaji: 'karera', meaning: 'Mereka (laki-laki)', category: 'basic' },
    { jp: 'かのじょたち', romaji: 'kanojotachi', meaning: 'Mereka (perempuan)', category: 'basic' },
    { jp: 'きみ', romaji: 'kimi', meaning: 'Kamu', category: 'basic' },
    { jp: 'ひと', romaji: 'hito', meaning: 'Orang', category: 'basic' },
    { jp: 'がくせい', romaji: 'gakusei', meaning: 'Murid', category: 'basic' },
    { jp: 'せんせい', romaji: 'sensei', meaning: 'Guru', category: 'basic' },
    { jp: 'ともだち', romaji: 'tomodachi', meaning: 'Teman', category: 'basic' },
    { jp: 'しにゅう', romaji: 'shinyuu', meaning: 'Sahabat dekat', category: 'basic' },
    { jp: 'こいびと', romaji: 'koibito', meaning: 'Pasangan / Kekasih', category: 'basic' },
    { jp: 'こども', romaji: 'kodomo', meaning: 'Anak-anak', category: 'basic' },
    { jp: 'なに', romaji: 'nani', meaning: 'Apa', category: 'basic' },
    { jp: 'はい', romaji: 'hai', meaning: 'Ya', category: 'basic' },
    { jp: 'でも', romaji: 'demo', meaning: 'Tapi', category: 'basic' },
    { jp: 'ほん', romaji: 'hon', meaning: 'Buku', category: 'basic' },
    { jp: 'じしょ', romaji: 'jisho', meaning: 'Kamus', category: 'basic' },
    { jp: 'あなた', romaji: 'anata', meaning: 'Kamu (formal)', category: 'basic' },
    { jp: 'かれ', romaji: 'kare', meaning: 'Dia (laki-laki)', category: 'basic' },
    { jp: 'かのじょ', romaji: 'kanojo', meaning: 'Dia (perempuan)', category: 'basic' },
    { jp: 'わたしたち', romaji: 'watashitachi', meaning: 'Kami / Kita', category: 'basic' },
    { jp: 'みなさん', romaji: 'minasan', meaning: 'Semua orang (sopan)', category: 'basic' },
    { jp: 'だれ', romaji: 'dare', meaning: 'Siapa', category: 'basic' },
    { jp: 'どなた', romaji: 'donata', meaning: 'Siapa (formal)', category: 'basic' },
    { jp: 'いつ', romaji: 'itsu', meaning: 'Kapan', category: 'basic' },
    { jp: 'どこ', romaji: 'doko', meaning: 'Di mana', category: 'basic' },
    { jp: 'どちら', romaji: 'dochira', meaning: 'Yang mana / Ke mana', category: 'basic' },
    { jp: 'どれ', romaji: 'dore', meaning: 'Yang mana (benda)', category: 'basic' },
    { jp: 'どの', romaji: 'dono', meaning: 'Yang mana (+kata benda)', category: 'basic' },
    { jp: 'どう', romaji: 'dou', meaning: 'Bagaimana', category: 'basic' },
    { jp: 'どうして', romaji: 'doushite', meaning: 'Kenapa', category: 'basic' },
    { jp: 'なぜ', romaji: 'naze', meaning: 'Mengapa', category: 'basic' },
    { jp: 'いくつ', romaji: 'ikutsu', meaning: 'Berapa (jumlah)', category: 'basic' },
    { jp: 'いくら', romaji: 'ikura', meaning: 'Berapa (harga)', category: 'basic' },
    { jp: 'これ', romaji: 'kore', meaning: 'Ini', category: 'basic' },
    { jp: 'それ', romaji: 'sore', meaning: 'Itu', category: 'basic' },
    { jp: 'あれ', romaji: 'are', meaning: 'Itu (jauh)', category: 'basic' },
    { jp: 'この', romaji: 'kono', meaning: 'Ini (+kata benda)', category: 'basic' },
    { jp: 'その', romaji: 'sono', meaning: 'Itu (+kata benda)', category: 'basic' },
    { jp: 'あの', romaji: 'ano', meaning: 'Itu (+kata benda, jauh)', category: 'basic' },
    { jp: 'ここ', romaji: 'koko', meaning: 'Sini', category: 'basic' },
    { jp: 'そこ', romaji: 'soko', meaning: 'Situ', category: 'basic' },
    { jp: 'あそこ', romaji: 'asoko', meaning: 'Sana', category: 'basic' },
    { jp: 'こちら', romaji: 'kochira', meaning: 'Sini (sopan)', category: 'basic' },
    { jp: 'そちら', romaji: 'sochira', meaning: 'Situ (sopan)', category: 'basic' },
    { jp: 'あちら', romaji: 'achira', meaning: 'Sana (sopan)', category: 'basic' },
    { jp: 'いいえ', romaji: 'iie', meaning: 'Tidak', category: 'basic' },
    { jp: 'ぜんぶ', romaji: 'zenbu', meaning: 'Semua', category: 'basic' },
    { jp: 'いっしょ', romaji: 'issho', meaning: 'Bersama', category: 'basic' },
    { jp: 'ひとり', romaji: 'hitori', meaning: 'Sendirian', category: 'basic' },
    { jp: 'じぶん', romaji: 'jibun', meaning: 'Diri sendiri', category: 'basic' },
    { jp: 'なまえ', romaji: 'namae', meaning: 'Nama', category: 'basic' },
    { jp: 'しごと', romaji: 'shigoto', meaning: 'Pekerjaan', category: 'basic' },
    { jp: 'おかね', romaji: 'okane', meaning: 'Uang', category: 'basic' },
    { jp: 'じゅうしょ', romaji: 'juusho', meaning: 'Alamat', category: 'basic' },
    { jp: 'ゆめ', romaji: 'yume', meaning: 'Mimpi', category: 'basic' },
    { jp: 'きょうみ', romaji: 'kyoumi', meaning: 'Minat / Ketertarikan', category: 'basic' },
    { jp: 'たばこ', romaji: 'tabako', meaning: 'Rokok', category: 'basic' },
    { jp: 'かいしゃ', romaji: 'kaisha', meaning: 'Perusahaan', category: 'basic' },
    { jp: 'かいしゃいん', romaji: 'kaishain', meaning: 'Karyawan', category: 'basic' },
    { jp: 'しゃちょう', romaji: 'shachou', meaning: 'Direktur perusahaan', category: 'basic' },
    { jp: 'いしゃ', romaji: 'isha', meaning: 'Dokter', category: 'basic' },
    { jp: 'かんごし', romaji: 'kangoshi', meaning: 'Perawat', category: 'basic' },
    { jp: 'けいかん', romaji: 'keikan', meaning: 'Polisi', category: 'basic' },
    { jp: 'こうむいん', romaji: 'koumuin', meaning: 'Pegawai negeri', category: 'basic' },
    { jp: 'しゅふ', romaji: 'shufu', meaning: 'Ibu rumah tangga', category: 'basic' },
    { jp: 'うんてんしゅ', romaji: 'untenshu', meaning: 'Sopir', category: 'basic' },
    { jp: 'ごはん', romaji: 'gohan', meaning: 'Nasi', category: 'food' },
    { jp: 'みず', romaji: 'mizu', meaning: 'Air', category: 'food' },
    { jp: 'おちゃ', romaji: 'ocha', meaning: 'Teh', category: 'food' },
    { jp: 'パン', romaji: 'pan', meaning: 'Roti', category: 'food' },
    { jp: 'ピザ', romaji: 'piza', meaning: 'Pizza', category: 'food' },
    { jp: 'コーヒー', romaji: 'koohii', meaning: 'Kopi', category: 'food' },
    { jp: 'バナナ', romaji: 'banana', meaning: 'Pisang', category: 'food' },
    { jp: 'ケーキ', romaji: 'keeki', meaning: 'Kue', category: 'food' },
    { jp: 'アイスクリーム', romaji: 'aisukuriimu', meaning: 'Es krim', category: 'food' },
    { jp: 'ジュース', romaji: 'juusu', meaning: 'Jus', category: 'food' },
    { jp: 'サンドイッチ', romaji: 'sandoicchi', meaning: 'Sandwich', category: 'food' },
    { jp: 'チョコレート', romaji: 'chokoreeto', meaning: 'Cokelat', category: 'food' },
    { jp: 'ハンバーガー', romaji: 'hanbaagaa', meaning: 'Hamburger', category: 'food' },
    { jp: 'パスタ', romaji: 'pasuta', meaning: 'Pasta', category: 'food' },
    { jp: 'サラダ', romaji: 'sarada', meaning: 'Salad', category: 'food' },
    { jp: 'にく', romaji: 'niku', meaning: 'Daging', category: 'food' },
    { jp: 'ぎゅうにく', romaji: 'gyuuniku', meaning: 'Daging sapi', category: 'food' },
    { jp: 'ぶたにく', romaji: 'butaniku', meaning: 'Daging babi', category: 'food' },
    { jp: 'とりにく', romaji: 'toriniku', meaning: 'Daging ayam', category: 'food' },
    { jp: 'さかな', romaji: 'sakana', meaning: 'Ikan', category: 'food' },
    { jp: 'たまご', romaji: 'tamago', meaning: 'Telur', category: 'food' },
    { jp: 'やさい', romaji: 'yasai', meaning: 'Sayuran', category: 'food' },
    { jp: 'くだもの', romaji: 'kudamono', meaning: 'Buah', category: 'food' },
    { jp: 'りんご', romaji: 'ringo', meaning: 'Apel', category: 'food' },
    { jp: 'みかん', romaji: 'mikan', meaning: 'Jeruk', category: 'food' },
    { jp: 'ぶどう', romaji: 'budou', meaning: 'Anggur', category: 'food' },
    { jp: 'いちご', romaji: 'ichigo', meaning: 'Stroberi', category: 'food' },
    { jp: 'すいか', romaji: 'suika', meaning: 'Semangka', category: 'food' },
    { jp: 'トマト', romaji: 'tomato', meaning: 'Tomat', category: 'food' },
    { jp: 'じゃがいも', romaji: 'jagaimo', meaning: 'Kentang', category: 'food' },
    { jp: 'たまねぎ', romaji: 'tamanegi', meaning: 'Bawang bombai', category: 'food' },
    { jp: 'にんじん', romaji: 'ninjin', meaning: 'Wortel', category: 'food' },
    { jp: 'きゅうり', romaji: 'kyuuri', meaning: 'Timun', category: 'food' },
    { jp: 'パイナップル', romaji: 'painappuru', meaning: 'Nanas', category: 'food' },
    { jp: 'すし', romaji: 'sushi', meaning: 'Sushi', category: 'food' },
    { jp: 'てんぷら', romaji: 'tenpura', meaning: 'Tempura', category: 'food' },
    { jp: 'そば', romaji: 'soba', meaning: 'Mi soba', category: 'food' },
    { jp: 'うどん', romaji: 'udon', meaning: 'Mi udon', category: 'food' },
    { jp: 'ラーメン', romaji: 'raamen', meaning: 'Ramen', category: 'food' },
    { jp: 'みそしる', romaji: 'misoshiru', meaning: 'Sup miso', category: 'food' },
    { jp: 'たまごやき', romaji: 'tamagoyaki', meaning: 'Telur gulung', category: 'food' },
    { jp: 'おかし', romaji: 'okashi', meaning: 'Camilan', category: 'food' },
    { jp: 'ぎゅうにゅう', romaji: 'gyuunyuu', meaning: 'Susu', category: 'food' },
    { jp: 'さとう', romaji: 'satou', meaning: 'Gula', category: 'food' },
    { jp: 'しお', romaji: 'shio', meaning: 'Garam', category: 'food' },
    { jp: 'しょうゆ', romaji: 'shouyu', meaning: 'Kecap asin', category: 'food' },
    { jp: 'あぶら', romaji: 'abura', meaning: 'Minyak', category: 'food' },
    { jp: 'こめ', romaji: 'kome', meaning: 'Beras', category: 'food' },
    { jp: 'あさごはん', romaji: 'asagohan', meaning: 'Sarapan', category: 'food' },
    { jp: 'ひるごはん', romaji: 'hirugohan', meaning: 'Makan siang', category: 'food' },
    { jp: 'ばんごはん', romaji: 'bangohan', meaning: 'Makan malam', category: 'food' },
    { jp: 'ゆうしょく', romaji: 'yuushoku', meaning: 'Makan malam (formal)', category: 'food' },
    { jp: 'おべんとう', romaji: 'obentou', meaning: 'Bekal makan siang', category: 'food' },
    { jp: 'ワイン', romaji: 'wain', meaning: 'Anggur (minuman)', category: 'food' },
    { jp: 'ビール', romaji: 'biiru', meaning: 'Bir', category: 'food' },
    { jp: 'スープ', romaji: 'suupu', meaning: 'Sup', category: 'food' },
    { jp: 'おさけ', romaji: 'osake', meaning: 'Minuman beralkohol', category: 'food' },
    { jp: 'かぞく', romaji: 'kazoku', meaning: 'Keluarga', category: 'family' },
    { jp: 'おとうさん', romaji: 'otousan', meaning: 'Ayah', category: 'family' },
    { jp: 'おかあさん', romaji: 'okaasan', meaning: 'Ibu', category: 'family' },
    { jp: 'おにいさん', romaji: 'oniisan', meaning: 'Kakak Laki-laki', category: 'family' },
    { jp: 'おねえさん', romaji: 'oneesan', meaning: 'Kakak Perempuan', category: 'family' },
    { jp: 'おじいさん', romaji: 'ojiisan', meaning: 'Kakek', category: 'family' },
    { jp: 'おばあさん', romaji: 'obaasan', meaning: 'Nenek', category: 'family' },
    { jp: 'おじさん', romaji: 'ojisan', meaning: 'Paman', category: 'family' },
    { jp: 'おばさん', romaji: 'obasan', meaning: 'Bibi', category: 'family' },
    { jp: 'ちち', romaji: 'chichi', meaning: 'Ayah (keluarga sendiri)', category: 'family' },
    { jp: 'はは', romaji: 'haha', meaning: 'Ibu (keluarga sendiri)', category: 'family' },
    { jp: 'あに', romaji: 'ani', meaning: 'Kakak laki-laki (keluarga sendiri)', category: 'family' },
    { jp: 'あね', romaji: 'ane', meaning: 'Kakak perempuan (keluarga sendiri)', category: 'family' },
    { jp: 'おとうと', romaji: 'otouto', meaning: 'Adik laki-laki', category: 'family' },
    { jp: 'いもうと', romaji: 'imouto', meaning: 'Adik perempuan', category: 'family' },
    { jp: 'むすこ', romaji: 'musuko', meaning: 'Anak laki-laki', category: 'family' },
    { jp: 'むすめ', romaji: 'musume', meaning: 'Anak perempuan', category: 'family' },
    { jp: 'しゅじん', romaji: 'shujin', meaning: 'Suami', category: 'family' },
    { jp: 'おっと', romaji: 'otto', meaning: 'Suami', category: 'family' },
    { jp: 'つま', romaji: 'tsuma', meaning: 'Istri', category: 'family' },
    { jp: 'かない', romaji: 'kanai', meaning: 'Istri (sendiri)', category: 'family' },
    { jp: 'そふ', romaji: 'sofu', meaning: 'Kakek (keluarga sendiri)', category: 'family' },
    { jp: 'そぼ', romaji: 'sobo', meaning: 'Nenek (keluarga sendiri)', category: 'family' },
    { jp: 'いとこ', romaji: 'itoko', meaning: 'Sepupu', category: 'family' },
    { jp: 'まご', romaji: 'mago', meaning: 'Cucu', category: 'family' },
    { jp: 'いち', romaji: 'ichi', meaning: 'Satu', category: 'numbers' },
    { jp: 'に', romaji: 'ni', meaning: 'Dua', category: 'numbers' },
    { jp: 'さん', romaji: 'san', meaning: 'Tiga', category: 'numbers' },
    { jp: 'し', romaji: 'shi', meaning: 'Empat', category: 'numbers' },
    { jp: 'よん', romaji: 'yon', meaning: 'Empat', category: 'numbers' },
    { jp: 'ご', romaji: 'go', meaning: 'Lima', category: 'numbers' },
    { jp: 'ろく', romaji: 'roku', meaning: 'Enam', category: 'numbers' },
    { jp: 'しち', romaji: 'shichi', meaning: 'Tujuh', category: 'numbers' },
    { jp: 'なな', romaji: 'nana', meaning: 'Tujuh', category: 'numbers' },
    { jp: 'はち', romaji: 'hachi', meaning: 'Delapan', category: 'numbers' },
    { jp: 'きゅう', romaji: 'kyuu', meaning: 'Sembilan', category: 'numbers' },
    { jp: 'く', romaji: 'ku', meaning: 'Sembilan', category: 'numbers' },
    { jp: 'じゅう', romaji: 'juu', meaning: 'Sepuluh', category: 'numbers' },
    { jp: 'ひゃく', romaji: 'hyaku', meaning: 'Seratus', category: 'numbers' },
    { jp: 'せん', romaji: 'sen', meaning: 'Seribu', category: 'numbers' },
    { jp: 'まん', romaji: 'man', meaning: 'Sepuluh ribu', category: 'numbers' },
    { jp: 'じゅういち', romaji: 'juuichi', meaning: 'Sebelas', category: 'numbers' },
    { jp: 'じゅうに', romaji: 'juuni', meaning: 'Dua belas', category: 'numbers' },
    { jp: 'にじゅう', romaji: 'nijuu', meaning: 'Dua puluh', category: 'numbers' },
    { jp: 'さんじゅう', romaji: 'sanjuu', meaning: 'Tiga puluh', category: 'numbers' },
    { jp: 'よんじゅう', romaji: 'yonjuu', meaning: 'Empat puluh', category: 'numbers' },
    { jp: 'ごじゅう', romaji: 'gojuu', meaning: 'Lima puluh', category: 'numbers' },
    { jp: 'ひゃくまん', romaji: 'hyakuman', meaning: 'Sejuta', category: 'numbers' },
    { jp: 'ぜろ', romaji: 'zero', meaning: 'Nol', category: 'numbers' },
    { jp: 'れい', romaji: 'rei', meaning: 'Nol', category: 'numbers' },
    { jp: 'はんぶん', romaji: 'hanbun', meaning: 'Setengah', category: 'numbers' },
    { jp: 'ひとつ', romaji: 'hitotsu', meaning: 'Satu (benda)', category: 'counters' },
    { jp: 'ふたつ', romaji: 'futatsu', meaning: 'Dua (benda)', category: 'counters' },
    { jp: 'みっつ', romaji: 'mittsu', meaning: 'Tiga (benda)', category: 'counters' },
    { jp: 'よっつ', romaji: 'yottsu', meaning: 'Empat (benda)', category: 'counters' },
    { jp: 'いつつ', romaji: 'itsutsu', meaning: 'Lima (benda)', category: 'counters' },
    { jp: 'むっつ', romaji: 'muttsu', meaning: 'Enam (benda)', category: 'counters' },
    { jp: 'ななつ', romaji: 'nanatsu', meaning: 'Tujuh (benda)', category: 'counters' },
    { jp: 'やっつ', romaji: 'yattsu', meaning: 'Delapan (benda)', category: 'counters' },
    { jp: 'ここのつ', romaji: 'kokonotsu', meaning: 'Sembilan (benda)', category: 'counters' },
    { jp: 'とお', romaji: 'too', meaning: 'Sepuluh (benda)', category: 'counters' },
    { jp: 'ふたり', romaji: 'futari', meaning: 'Dua orang', category: 'counters' },
    { jp: 'さんにん', romaji: 'sannin', meaning: 'Tiga orang', category: 'counters' },
    { jp: 'よにん', romaji: 'yonin', meaning: 'Empat orang', category: 'counters' },
    { jp: 'いっぽん', romaji: 'ippon', meaning: 'Satu batang', category: 'counters' },
    { jp: 'にほん', romaji: 'nihon', meaning: 'Dua batang', category: 'counters' },
    { jp: 'いっかい', romaji: 'ikkai', meaning: 'Satu kali / Lantai satu', category: 'counters' },
    { jp: 'にかい', romaji: 'nikai', meaning: 'Dua kali / Lantai dua', category: 'counters' },
    { jp: 'いちまい', romaji: 'ichimai', meaning: 'Satu lembar', category: 'counters' },
    { jp: 'にまい', romaji: 'nimai', meaning: 'Dua lembar', category: 'counters' },
    { jp: 'いっさつ', romaji: 'issatsu', meaning: 'Satu buku', category: 'counters' },
    { jp: 'いっぴき', romaji: 'ippiki', meaning: 'Satu ekor (kecil)', category: 'counters' },
    { jp: 'いちだい', romaji: 'ichidai', meaning: 'Satu unit (mesin)', category: 'counters' },
    { jp: 'なんにん', romaji: 'nannin', meaning: 'Berapa orang', category: 'counters' },
    { jp: 'なんまい', romaji: 'nanmai', meaning: 'Berapa lembar', category: 'counters' },
    { jp: 'なんぼん', romaji: 'nanbon', meaning: 'Berapa batang', category: 'counters' },
    { jp: 'さい', romaji: 'sai', meaning: 'Umur (tahun)', category: 'counters' },
    { jp: 'かい', romaji: 'kai', meaning: 'Kali (frekuensi)', category: 'counters' },
    { jp: 'ふん', romaji: 'fun', meaning: 'Menit', category: 'counters' },
    { jp: 'じかん', romaji: 'jikan', meaning: 'Jam (durasi)', category: 'counters' },
    { jp: 'きょう', romaji: 'kyou', meaning: 'Hari ini', category: 'time' },
    { jp: 'きのう', romaji: 'kinou', meaning: 'Kemarin', category: 'time' },
    { jp: 'あした', romaji: 'ashita', meaning: 'Besok', category: 'time' },
    { jp: 'あさって', romaji: 'asatte', meaning: 'Lusa', category: 'time' },
    { jp: 'あさ', romaji: 'asa', meaning: 'Pagi', category: 'time' },
    { jp: 'ひる', romaji: 'hiru', meaning: 'Siang', category: 'time' },
    { jp: 'よる', romaji: 'yoru', meaning: 'Malam', category: 'time' },
    { jp: 'つき', romaji: 'tsuki', meaning: 'Bulan', category: 'time' },
    { jp: 'とし', romaji: 'toshi', meaning: 'Tahun', category: 'time' },
    { jp: 'まいにち', romaji: 'mainichi', meaning: 'Setiap hari', category: 'time' },
    { jp: 'まいあさ', romaji: 'maiasa', meaning: 'Setiap pagi', category: 'time' },
    { jp: 'まいばん', romaji: 'maiban', meaning: 'Setiap malam', category: 'time' },
    { jp: 'まいしゅう', romaji: 'maishuu', meaning: 'Setiap minggu', category: 'time' },
    { jp: 'まいつき', romaji: 'maitsuki', meaning: 'Setiap bulan', category: 'time' },
    { jp: 'まいとし', romaji: 'maitoshi', meaning: 'Setiap tahun', category: 'time' },
    { jp: 'こんしゅう', romaji: 'konshuu', meaning: 'Minggu ini', category: 'time' },
    { jp: 'せんしゅう', romaji: 'senshuu', meaning: 'Minggu lalu', category: 'time' },
    { jp: 'らいしゅう', romaji: 'raishuu', meaning: 'Minggu depan', category: 'time' },
    { jp: 'こんげつ', romaji: 'kongetsu', meaning: 'Bulan ini', category: 'time' },
    { jp: 'せんげつ', romaji: 'sengetsu', meaning: 'Bulan lalu', category: 'time' },
    { jp: 'らいげつ', romaji: 'raigetsu', meaning: 'Bulan depan', category: 'time' },
    { jp: 'ことし', romaji: 'kotoshi', meaning: 'Tahun ini', category: 'time' },
    { jp: 'きょねん', romaji: 'kyonen', meaning: 'Tahun lalu', category: 'time' },
    { jp: 'らいねん', romaji: 'rainen', meaning: 'Tahun depan', category: 'time' },
    { jp: 'けさ', romaji: 'kesa', meaning: 'Pagi ini', category: 'time' },
    { jp: 'こんばん', romaji: 'konban', meaning: 'Malam ini', category: 'time' },
    { jp: 'ゆうべ', romaji: 'yuube', meaning: 'Tadi malam', category: 'time' },
    { jp: 'にちようび', romaji: 'nichiyoubi', meaning: 'Hari Minggu', category: 'time' },
    { jp: 'げつようび', romaji: 'getsuyoubi', meaning: 'Hari Senin', category: 'time' },
    { jp: 'かようび', romaji: 'kayoubi', meaning: 'Hari Selasa', category: 'time' },
    { jp: 'すいようび', romaji: 'suiyoubi', meaning: 'Hari Rabu', category: 'time' },
    { jp: 'もくようび', romaji: 'mokuyoubi', meaning: 'Hari Kamis', category: 'time' },
    { jp: 'きんようび', romaji: 'kinyoubi', meaning: 'Hari Jumat', category: 'time' },
    { jp: 'どようび', romaji: 'doyoubi', meaning: 'Hari Sabtu', category: 'time' },
    { jp: 'いちがつ', romaji: 'ichigatsu', meaning: 'Januari', category: 'time' },
    { jp: 'にがつ', romaji: 'nigatsu', meaning: 'Februari', category: 'time' },
    { jp: 'さんがつ', romaji: 'sangatsu', meaning: 'Maret', category: 'time' },
    { jp: 'しがつ', romaji: 'shigatsu', meaning: 'April', category: 'time' },
    { jp: 'ごがつ', romaji: 'gogatsu', meaning: 'Mei', category: 'time' },
    { jp: 'ろくがつ', romaji: 'rokugatsu', meaning: 'Juni', category: 'time' },
    { jp: 'しちがつ', romaji: 'shichigatsu', meaning: 'Juli', category: 'time' },
    { jp: 'はちがつ', romaji: 'hachigatsu', meaning: 'Agustus', category: 'time' },
    { jp: 'くがつ', romaji: 'kugatsu', meaning: 'September', category: 'time' },
    { jp: 'じゅうがつ', romaji: 'juugatsu', meaning: 'Oktober', category: 'time' },
    { jp: 'じゅういちがつ', romaji: 'juuichigatsu', meaning: 'November', category: 'time' },
    { jp: 'じゅうにがつ', romaji: 'juunigatsu', meaning: 'Desember', category: 'time' },
    { jp: 'いま', romaji: 'ima', meaning: 'Sekarang', category: 'time' },
    { jp: 'まえ', romaji: 'mae', meaning: 'Sebelum', category: 'time' },
    { jp: 'あと', romaji: 'ato', meaning: 'Sesudah', category: 'time' },
    { jp: 'はんとし', romaji: 'hantoshi', meaning: 'Setengah tahun', category: 'time' },
    { jp: 'しゅうまつ', romaji: 'shuumatsu', meaning: 'Akhir pekan', category: 'time' },
    { jp: 'たんじょうび', romaji: 'tanjoubi', meaning: 'Hari ulang tahun', category: 'time' },
    { jp: 'なつやすみ', romaji: 'natsuyasumi', meaning: 'Libur musim panas', category: 'time' },
    { jp: 'ふゆやすみ', romaji: 'fuyuyasumi', meaning: 'Libur musim dingin', category: 'time' },
    { jp: 'はる', romaji: 'haru', meaning: 'Musim semi', category: 'time' },
    { jp: 'なつ', romaji: 'natsu', meaning: 'Musim panas', category: 'time' },
    { jp: 'あき', romaji: 'aki', meaning: 'Musim gugur', category: 'time' },
    { jp: 'ふゆ', romaji: 'fuyu', meaning: 'Musim dingin', category: 'time' },
    { jp: 'おいしい', romaji: 'oishii', meaning: 'Enak / Lezat', category: 'adjectives' },
    { jp: 'こわい', romaji: 'kowai', meaning: 'Seram / Menakutkan', category: 'adjectives' },
    { jp: 'たのしい', romaji: 'tanoshii', meaning: 'Seru / Menyenangkan', category: 'adjectives' },
    { jp: 'きらい', romaji: 'kirai', meaning: 'Benci', category: 'adjectives' },
    { jp: 'すき', romaji: 'suki', meaning: 'Suka', category: 'adjectives' },
    { jp: 'かなしい', romaji: 'kanashii', meaning: 'Sedih', category: 'adjectives' },
    { jp: 'ながい', romaji: 'nagai', meaning: 'Panjang', category: 'adjectives' },
    { jp: 'みじかい', romaji: 'mijikai', meaning: 'Pendek', category: 'adjectives' },
    { jp: 'あたらしい', romaji: 'atarashii', meaning: 'Baru', category: 'adjectives' },
    { jp: 'ふるい', romaji: 'furui', meaning: 'Lama', category: 'adjectives' },
    { jp: 'おおきい', romaji: 'ookii', meaning: 'Besar', category: 'adjectives' },
    { jp: 'ちいさい', romaji: 'chiisai', meaning: 'Kecil', category: 'adjectives' },
    { jp: 'たかい', romaji: 'takai', meaning: 'Tinggi / Mahal', category: 'adjectives' },
    { jp: 'やすい', romaji: 'yasui', meaning: 'Murah', category: 'adjectives' },
    { jp: 'かわいい', romaji: 'kawaii', meaning: 'Imut', category: 'adjectives' },
    { jp: 'きれい', romaji: 'kirei', meaning: 'Cantik / Bersih', category: 'adjectives' },
    { jp: 'しろい', romaji: 'shiroi', meaning: 'Putih', category: 'adjectives' },
    { jp: 'くろい', romaji: 'kuroi', meaning: 'Hitam', category: 'adjectives' },
    { jp: 'あかい', romaji: 'akai', meaning: 'Merah', category: 'adjectives' },
    { jp: 'あおい', romaji: 'aoi', meaning: 'Biru', category: 'adjectives' },
    { jp: 'きいろい', romaji: 'kiiroi', meaning: 'Kuning', category: 'adjectives' },
    { jp: 'みどり', romaji: 'midori', meaning: 'Hijau', category: 'adjectives' },
    { jp: 'ちゃいろ', romaji: 'chairo', meaning: 'Coklat (warna)', category: 'adjectives' },
    { jp: 'むずかしい', romaji: 'muzukashii', meaning: 'Sulit', category: 'adjectives' },
    { jp: 'やさしい', romaji: 'yasashii', meaning: 'Mudah / Baik hati', category: 'adjectives' },
    { jp: 'かんたん', romaji: 'kantan', meaning: 'Sederhana / Mudah', category: 'adjectives' },
    { jp: 'あつい', romaji: 'atsui', meaning: 'Panas', category: 'adjectives' },
    { jp: 'さむい', romaji: 'samui', meaning: 'Dingin (cuaca)', category: 'adjectives' },
    { jp: 'つめたい', romaji: 'tsumetai', meaning: 'Dingin (benda)', category: 'adjectives' },
    { jp: 'あたたかい', romaji: 'atatakai', meaning: 'Hangat', category: 'adjectives' },
    { jp: 'すずしい', romaji: 'suzushii', meaning: 'Sejuk', category: 'adjectives' },
    { jp: 'おもい', romaji: 'omoi', meaning: 'Berat', category: 'adjectives' },
    { jp: 'かるい', romaji: 'karui', meaning: 'Ringan', category: 'adjectives' },
    { jp: 'はやい', romaji: 'hayai', meaning: 'Cepat / Pagi', category: 'adjectives' },
    { jp: 'おそい', romaji: 'osoi', meaning: 'Lambat / Terlambat', category: 'adjectives' },
    { jp: 'いそがしい', romaji: 'isogashii', meaning: 'Sibuk', category: 'adjectives' },
    { jp: 'ひまな', romaji: 'himana', meaning: 'Senggang / Luang', category: 'adjectives' },
    { jp: 'げんきな', romaji: 'genkina', meaning: 'Sehat / Bersemangat', category: 'adjectives' },
    { jp: 'しずかな', romaji: 'shizukana', meaning: 'Tenang / Sepi', category: 'adjectives' },
    { jp: 'にぎやかな', romaji: 'nigiyakana', meaning: 'Ramai', category: 'adjectives' },
    { jp: 'しんせつな', romaji: 'shinsetsuna', meaning: 'Baik hati / Ramah', category: 'adjectives' },
    { jp: 'べんりな', romaji: 'benrina', meaning: 'Praktis', category: 'adjectives' },
    { jp: 'ふべんな', romaji: 'fubenna', meaning: 'Tidak praktis', category: 'adjectives' },
    { jp: 'じょうずな', romaji: 'jouzuna', meaning: 'Pandai / Mahir', category: 'adjectives' },
    { jp: 'へたな', romaji: 'hetana', meaning: 'Tidak mahir', category: 'adjectives' },
    { jp: 'すきな', romaji: 'sukina', meaning: 'Disukai', category: 'adjectives' },
    { jp: 'きらいな', romaji: 'kiraina', meaning: 'Dibenci', category: 'adjectives' },
    { jp: 'ゆうめいな', romaji: 'yuumeina', meaning: 'Terkenal', category: 'adjectives' },
    { jp: 'たいせつな', romaji: 'taisetsuna', meaning: 'Penting', category: 'adjectives' },
    { jp: 'だいじょうぶな', romaji: 'daijoubuna', meaning: 'Baik-baik saja', category: 'adjectives' },
    { jp: 'いろいろな', romaji: 'iroirona', meaning: 'Bermacam-macam', category: 'adjectives' },
    { jp: 'いっぱいの', romaji: 'ippaino', meaning: 'Penuh', category: 'adjectives' },
    { jp: 'おおぜい', romaji: 'oozei', meaning: 'Banyak orang', category: 'adjectives' },
    { jp: 'おおい', romaji: 'ooi', meaning: 'Banyak', category: 'adjectives' },
    { jp: 'すくない', romaji: 'sukunai', meaning: 'Sedikit', category: 'adjectives' },
    { jp: 'ちかい', romaji: 'chikai', meaning: 'Dekat', category: 'adjectives' },
    { jp: 'とおい', romaji: 'tooi', meaning: 'Jauh', category: 'adjectives' },
    { jp: 'ひろい', romaji: 'hiroi', meaning: 'Luas', category: 'adjectives' },
    { jp: 'せまい', romaji: 'semai', meaning: 'Sempit', category: 'adjectives' },
    { jp: 'ふかい', romaji: 'fukai', meaning: 'Dalam', category: 'adjectives' },
    { jp: 'あさい', romaji: 'asai', meaning: 'Dangkal', category: 'adjectives' },
    { jp: 'あかるい', romaji: 'akarui', meaning: 'Terang', category: 'adjectives' },
    { jp: 'くらい', romaji: 'kurai', meaning: 'Gelap', category: 'adjectives' },
    { jp: 'うれしい', romaji: 'ureshii', meaning: 'Senang / Bahagia', category: 'adjectives' },
    { jp: 'さびしい', romaji: 'sabishii', meaning: 'Kesepian', category: 'adjectives' },
    { jp: 'いたい', romaji: 'itai', meaning: 'Sakit', category: 'adjectives' },
    { jp: 'ねむい', romaji: 'nemui', meaning: 'Mengantuk', category: 'adjectives' },
    { jp: 'つよい', romaji: 'tsuyoi', meaning: 'Kuat', category: 'adjectives' },
    { jp: 'よわい', romaji: 'yowai', meaning: 'Lemah', category: 'adjectives' },
    { jp: 'うるさい', romaji: 'urusai', meaning: 'Berisik', category: 'adjectives' },
    { jp: 'おかしい', romaji: 'okashii', meaning: 'Aneh / Lucu', category: 'adjectives' },
    { jp: 'まじめな', romaji: 'majimena', meaning: 'Rajin / Serius', category: 'adjectives' },
    { jp: 'らくな', romaji: 'rakuna', meaning: 'Santai / Nyaman', category: 'adjectives' },
    { jp: 'ひつような', romaji: 'hitsuyouna', meaning: 'Perlu', category: 'adjectives' },
    { jp: 'だいすきな', romaji: 'daisukina', meaning: 'Sangat suka', category: 'adjectives' },
    { jp: 'わかい', romaji: 'wakai', meaning: 'Muda', category: 'adjectives' },
    { jp: 'いい', romaji: 'ii', meaning: 'Bagus', category: 'adjectives' },
    { jp: 'よい', romaji: 'yoi', meaning: 'Bagus', category: 'adjectives' },
    { jp: 'わるい', romaji: 'warui', meaning: 'Buruk', category: 'adjectives' },
    { jp: 'あまい', romaji: 'amai', meaning: 'Manis', category: 'adjectives' },
    { jp: 'からい', romaji: 'karai', meaning: 'Pedas', category: 'adjectives' },
    { jp: 'にがい', romaji: 'nigai', meaning: 'Pahit', category: 'adjectives' },
    { jp: 'すっぱい', romaji: 'suppai', meaning: 'Asam', category: 'adjectives' },
    { jp: 'まずい', romaji: 'mazui', meaning: 'Tidak enak', category: 'adjectives' },
    { jp: 'たいへんな', romaji: 'taihenna', meaning: 'Berat / Susah', category: 'adjectives' },
    { jp: 'しんぱいな', romaji: 'shinpaina', meaning: 'Khawatir', category: 'adjectives' },
    { jp: 'おこる', romaji: 'okoru', meaning: 'Marah', category: 'verbs' },
    { jp: 'わらう', romaji: 'warau', meaning: 'Tertawa', category: 'verbs' },
    { jp: 'みる', romaji: 'miru', meaning: 'Melihat', category: 'verbs' },
    { jp: 'きく', romaji: 'kiku', meaning: 'Mendengar', category: 'verbs' },
    { jp: 'たべる', romaji: 'taberu', meaning: 'Makan', category: 'verbs' },
    { jp: 'のむ', romaji: 'nomu', meaning: 'Minum', category: 'verbs' },
    { jp: 'ねる', romaji: 'neru', meaning: 'Tidur', category: 'verbs' },
    { jp: 'いく', romaji: 'iku', meaning: 'Pergi', category: 'verbs' },
    { jp: 'くる', romaji: 'kuru', meaning: 'Datang', category: 'verbs' },
    { jp: 'かう', romaji: 'kau', meaning: 'Membeli', category: 'verbs' },
    { jp: 'よむ', romaji: 'yomu', meaning: 'Membaca', category: 'verbs' },
    { jp: 'かく', romaji: 'kaku', meaning: 'Menulis', category: 'verbs' },
    { jp: 'はなす', romaji: 'hanasu', meaning: 'Berbicara', category: 'verbs' },
    { jp: 'べんきょうする', romaji: 'benkyou suru', meaning: 'Belajar', category: 'verbs' },
    { jp: 'おきる', romaji: 'okiru', meaning: 'Bangun tidur', category: 'verbs' },
    { jp: 'かえる', romaji: 'kaeru', meaning: 'Pulang', category: 'verbs' },
    { jp: 'でる', romaji: 'deru', meaning: 'Keluar', category: 'verbs' },
    { jp: 'はいる', romaji: 'hairu', meaning: 'Masuk', category: 'verbs' },
    { jp: 'あるく', romaji: 'aruku', meaning: 'Berjalan kaki', category: 'verbs' },
    { jp: 'はしる', romaji: 'hashiru', meaning: 'Berlari', category: 'verbs' },
    { jp: 'とまる', romaji: 'tomaru', meaning: 'Berhenti', category: 'verbs' },
    { jp: 'すわる', romaji: 'suwaru', meaning: 'Duduk', category: 'verbs' },
    { jp: 'たつ', romaji: 'tatsu', meaning: 'Berdiri', category: 'verbs' },
    { jp: 'あける', romaji: 'akeru', meaning: 'Membuka', category: 'verbs' },
    { jp: 'しめる', romaji: 'shimeru', meaning: 'Menutup', category: 'verbs' },
    { jp: 'あらう', romaji: 'arau', meaning: 'Mencuci', category: 'verbs' },
    { jp: 'つくる', romaji: 'tsukuru', meaning: 'Membuat', category: 'verbs' },
    { jp: 'うたう', romaji: 'utau', meaning: 'Bernyanyi', category: 'verbs' },
    { jp: 'おどる', romaji: 'odoru', meaning: 'Menari', category: 'verbs' },
    { jp: 'あそぶ', romaji: 'asobu', meaning: 'Bermain', category: 'verbs' },
    { jp: 'およぐ', romaji: 'oyogu', meaning: 'Berenang', category: 'verbs' },
    { jp: 'のぼる', romaji: 'noboru', meaning: 'Mendaki / Naik', category: 'verbs' },
    { jp: 'おりる', romaji: 'oriru', meaning: 'Turun', category: 'verbs' },
    { jp: 'もつ', romaji: 'motsu', meaning: 'Membawa / Memegang', category: 'verbs' },
    { jp: 'おす', romaji: 'osu', meaning: 'Mendorong', category: 'verbs' },
    { jp: 'ひく', romaji: 'hiku', meaning: 'Menarik', category: 'verbs' },
    { jp: 'わたす', romaji: 'watasu', meaning: 'Menyerahkan', category: 'verbs' },
    { jp: 'かりる', romaji: 'kariru', meaning: 'Meminjam', category: 'verbs' },
    { jp: 'かす', romaji: 'kasu', meaning: 'Meminjamkan', category: 'verbs' },
    { jp: 'かえす', romaji: 'kaesu', meaning: 'Mengembalikan', category: 'verbs' },
    { jp: 'おしえる', romaji: 'oshieru', meaning: 'Mengajar', category: 'verbs' },
    { jp: 'ならう', romaji: 'narau', meaning: 'Belajar (dari orang)', category: 'verbs' },
    { jp: 'わすれる', romaji: 'wasureru', meaning: 'Melupakan', category: 'verbs' },
    { jp: 'おぼえる', romaji: 'oboeru', meaning: 'Mengingat', category: 'verbs' },
    { jp: 'しる', romaji: 'shiru', meaning: 'Mengetahui', category: 'verbs' },
    { jp: 'おもう', romaji: 'omou', meaning: 'Berpikir', category: 'verbs' },
    { jp: 'つかう', romaji: 'tsukau', meaning: 'Menggunakan', category: 'verbs' },
    { jp: 'まつ', romaji: 'matsu', meaning: 'Menunggu', category: 'verbs' },
    { jp: 'あう', romaji: 'au', meaning: 'Bertemu', category: 'verbs' },
    { jp: 'けっこんする', romaji: 'kekkon suru', meaning: 'Menikah', category: 'verbs' },
    { jp: 'はたらく', romaji: 'hataraku', meaning: 'Bekerja', category: 'verbs' },
    { jp: 'やすむ', romaji: 'yasumu', meaning: 'Istirahat', category: 'verbs' },
    { jp: 'つかれる', romaji: 'tsukareru', meaning: 'Lelah', category: 'verbs' },
    { jp: 'かんがえる', romaji: 'kangaeru', meaning: 'Memikirkan', category: 'verbs' },
    { jp: 'わかる', romaji: 'wakaru', meaning: 'Mengerti', category: 'verbs' },
    { jp: 'できる', romaji: 'dekiru', meaning: 'Bisa / Mampu', category: 'verbs' },
    { jp: 'すむ', romaji: 'sumu', meaning: 'Tinggal (di suatu tempat)', category: 'verbs' },
    { jp: 'うまれる', romaji: 'umareru', meaning: 'Lahir', category: 'verbs' },
    { jp: 'しぬ', romaji: 'shinu', meaning: 'Meninggal', category: 'verbs' },
    { jp: 'いる', romaji: 'iru', meaning: 'Ada (makhluk hidup)', category: 'verbs' },
    { jp: 'ある', romaji: 'aru', meaning: 'Ada (benda)', category: 'verbs' },
    { jp: 'あげる', romaji: 'ageru', meaning: 'Memberi', category: 'verbs' },
    { jp: 'もらう', romaji: 'morau', meaning: 'Menerima', category: 'verbs' },
    { jp: 'くれる', romaji: 'kureru', meaning: 'Diberi (dari orang lain)', category: 'verbs' },
    { jp: 'かかる', romaji: 'kakaru', meaning: 'Memakan (waktu/biaya)', category: 'verbs' },
    { jp: 'うる', romaji: 'uru', meaning: 'Menjual', category: 'verbs' },
    { jp: 'はじまる', romaji: 'hajimaru', meaning: 'Dimulai', category: 'verbs' },
    { jp: 'おわる', romaji: 'owaru', meaning: 'Selesai', category: 'verbs' },
    { jp: 'つく', romaji: 'tsuku', meaning: 'Tiba / Sampai', category: 'verbs' },
    { jp: 'のる', romaji: 'noru', meaning: 'Menaiki', category: 'verbs' },
    { jp: 'あびる', romaji: 'abiru', meaning: 'Mandi (shower)', category: 'verbs' },
    { jp: 'みがく', romaji: 'migaku', meaning: 'Menggosok (gigi)', category: 'verbs' },
    { jp: 'きる', romaji: 'kiru', meaning: 'Memakai (baju) / Memotong', category: 'verbs' },
    { jp: 'ぬぐ', romaji: 'nugu', meaning: 'Melepas (baju)', category: 'verbs' },
    { jp: 'かぶる', romaji: 'kaburu', meaning: 'Memakai (topi)', category: 'verbs' },
    { jp: 'はく', romaji: 'haku', meaning: 'Memakai (celana/sepatu)', category: 'verbs' },
    { jp: 'かける', romaji: 'kakeru', meaning: 'Memakai (kacamata) / Menelepon', category: 'verbs' },
    { jp: 'そうじする', romaji: 'souji suru', meaning: 'Membersihkan', category: 'verbs' },
    { jp: 'せんたくする', romaji: 'sentaku suru', meaning: 'Mencuci baju', category: 'verbs' },
    { jp: 'りょうりする', romaji: 'ryouri suru', meaning: 'Memasak', category: 'verbs' },
    { jp: 'てつだう', romaji: 'tetsudau', meaning: 'Membantu', category: 'verbs' },
    { jp: 'うんてんする', romaji: 'unten suru', meaning: 'Menyetir', category: 'verbs' },
    { jp: 'あがる', romaji: 'agaru', meaning: 'Naik', category: 'verbs' },
    { jp: 'さがる', romaji: 'sagaru', meaning: 'Turun / Mundur', category: 'verbs' },
    { jp: 'かつ', romaji: 'katsu', meaning: 'Menang', category: 'verbs' },
    { jp: 'まける', romaji: 'makeru', meaning: 'Kalah', category: 'verbs' },
    { jp: 'さく', romaji: 'saku', meaning: 'Mekar', category: 'verbs' },
    { jp: 'ふる', romaji: 'furu', meaning: 'Turun (hujan/salju)', category: 'verbs' },
    { jp: 'やむ', romaji: 'yamu', meaning: 'Berhenti (hujan)', category: 'verbs' },
    { jp: 'すぎる', romaji: 'sugiru', meaning: 'Melewati / Berlebihan', category: 'verbs' },
    { jp: 'さがす', romaji: 'sagasu', meaning: 'Mencari', category: 'verbs' },
    { jp: 'みつける', romaji: 'mitsukeru', meaning: 'Menemukan', category: 'verbs' },
    { jp: 'なくす', romaji: 'nakusu', meaning: 'Kehilangan', category: 'verbs' },
    { jp: 'こまる', romaji: 'komaru', meaning: 'Kesulitan / Bingung', category: 'verbs' },
    { jp: 'なく', romaji: 'naku', meaning: 'Menangis', category: 'verbs' },
    { jp: 'よぶ', romaji: 'yobu', meaning: 'Memanggil', category: 'verbs' },
    { jp: 'はこぶ', romaji: 'hakobu', meaning: 'Membawa (barang)', category: 'verbs' },
    { jp: 'かたづける', romaji: 'katazukeru', meaning: 'Membereskan', category: 'verbs' },
    { jp: 'しらべる', romaji: 'shiraberu', meaning: 'Memeriksa', category: 'verbs' },
    { jp: 'けす', romaji: 'kesu', meaning: 'Mematikan / Menghapus', category: 'verbs' },
    { jp: 'つける', romaji: 'tsukeru', meaning: 'Menyalakan', category: 'verbs' },
    { jp: 'なおす', romaji: 'naosu', meaning: 'Memperbaiki', category: 'verbs' },
    { jp: 'こわす', romaji: 'kowasu', meaning: 'Merusak', category: 'verbs' },
    { jp: 'こわれる', romaji: 'kowareru', meaning: 'Rusak', category: 'verbs' },
    { jp: 'とても', romaji: 'totemo', meaning: 'Sangat', category: 'adverbs' },
    { jp: 'すこし', romaji: 'sukoshi', meaning: 'Sedikit', category: 'adverbs' },
    { jp: 'ちょっと', romaji: 'chotto', meaning: 'Sebentar / Sedikit', category: 'adverbs' },
    { jp: 'たくさん', romaji: 'takusan', meaning: 'Banyak', category: 'adverbs' },
    { jp: 'ぜんぜん', romaji: 'zenzen', meaning: 'Sama sekali (tidak)', category: 'adverbs' },
    { jp: 'あまり', romaji: 'amari', meaning: 'Tidak terlalu', category: 'adverbs' },
    { jp: 'もっと', romaji: 'motto', meaning: 'Lebih', category: 'adverbs' },
    { jp: 'いちばん', romaji: 'ichiban', meaning: 'Paling / Nomor satu', category: 'adverbs' },
    { jp: 'また', romaji: 'mata', meaning: 'Lagi', category: 'adverbs' },
    { jp: 'もう', romaji: 'mou', meaning: 'Sudah', category: 'adverbs' },
    { jp: 'まだ', romaji: 'mada', meaning: 'Masih / Belum', category: 'adverbs' },
    { jp: 'すぐに', romaji: 'suguni', meaning: 'Segera', category: 'adverbs' },
    { jp: 'いつも', romaji: 'itsumo', meaning: 'Selalu', category: 'adverbs' },
    { jp: 'ときどき', romaji: 'tokidoki', meaning: 'Kadang-kadang', category: 'adverbs' },
    { jp: 'たいてい', romaji: 'taitei', meaning: 'Biasanya', category: 'adverbs' },
    { jp: 'よく', romaji: 'yoku', meaning: 'Sering / Dengan baik', category: 'adverbs' },
    { jp: 'はじめて', romaji: 'hajimete', meaning: 'Pertama kali', category: 'adverbs' },
    { jp: 'いっしょうけんめい', romaji: 'isshoukenmei', meaning: 'Dengan sungguh-sungguh', category: 'adverbs' },
    { jp: 'ゆっくり', romaji: 'yukkuri', meaning: 'Perlahan', category: 'adverbs' },
    { jp: 'はやく', romaji: 'hayaku', meaning: 'Dengan cepat', category: 'adverbs' },
    { jp: 'それから', romaji: 'sorekara', meaning: 'Setelah itu', category: 'adverbs' },
    { jp: 'それで', romaji: 'sorede', meaning: 'Oleh karena itu', category: 'adverbs' },
    { jp: 'しかし', romaji: 'shikashi', meaning: 'Akan tetapi', category: 'adverbs' },
    { jp: 'そして', romaji: 'soshite', meaning: 'Dan kemudian', category: 'adverbs' },
    { jp: 'だから', romaji: 'dakara', meaning: 'Karena itu', category: 'adverbs' },
    { jp: 'なぜなら', romaji: 'nazenara', meaning: 'Karena', category: 'adverbs' },
    { jp: 'たぶん', romaji: 'tabun', meaning: 'Mungkin', category: 'adverbs' },
    { jp: 'きっと', romaji: 'kitto', meaning: 'Pasti', category: 'adverbs' },
    { jp: 'ぜひ', romaji: 'zehi', meaning: 'Sangat berharap', category: 'adverbs' },
    { jp: 'いっぱい', romaji: 'ippai', meaning: 'Penuh sekali', category: 'adverbs' },
    { jp: 'ちゃんと', romaji: 'chanto', meaning: 'Dengan benar', category: 'adverbs' },
    { jp: 'べつに', romaji: 'betsuni', meaning: 'Tidak juga', category: 'adverbs' },
    { jp: 'とくに', romaji: 'tokuni', meaning: 'Terutama', category: 'adverbs' },
    { jp: 'がっこう', romaji: 'gakkou', meaning: 'Sekolah', category: 'places' },
    { jp: 'まち', romaji: 'machi', meaning: 'Kota', category: 'places' },
    { jp: 'いなか', romaji: 'inaka', meaning: 'Desa / Kampung', category: 'places' },
    { jp: 'くに', romaji: 'kuni', meaning: 'Negara', category: 'places' },
    { jp: 'みせ', romaji: 'mise', meaning: 'Toko / Kedai', category: 'places' },
    { jp: 'レストラン', romaji: 'resutoran', meaning: 'Restoran', category: 'places' },
    { jp: 'ホテル', romaji: 'hoteru', meaning: 'Hotel', category: 'places' },
    { jp: 'えき', romaji: 'eki', meaning: 'Stasiun', category: 'places' },
    { jp: 'こうえん', romaji: 'kouen', meaning: 'Taman', category: 'places' },
    { jp: 'びょういん', romaji: 'byouin', meaning: 'Rumah Sakit', category: 'places' },
    { jp: 'スーパー', romaji: 'suupaa', meaning: 'Supermarket', category: 'places' },
    { jp: 'コンビニ', romaji: 'konbini', meaning: 'Minimarket', category: 'places' },
    { jp: 'としょかん', romaji: 'toshokan', meaning: 'Perpustakaan', category: 'places' },
    { jp: 'うち', romaji: 'uchi', meaning: 'Rumah', category: 'places' },
    { jp: 'へや', romaji: 'heya', meaning: 'Kamar', category: 'places' },
    { jp: 'だいがく', romaji: 'daigaku', meaning: 'Universitas', category: 'places' },
    { jp: 'こうこう', romaji: 'koukou', meaning: 'SMA', category: 'places' },
    { jp: 'ちゅうがっこう', romaji: 'chuugakkou', meaning: 'SMP', category: 'places' },
    { jp: 'しょうがっこう', romaji: 'shougakkou', meaning: 'SD', category: 'places' },
    { jp: 'ようちえん', romaji: 'youchien', meaning: 'Taman kanak-kanak', category: 'places' },
    { jp: 'ぎんこう', romaji: 'ginkou', meaning: 'Bank', category: 'places' },
    { jp: 'ゆうびんきょく', romaji: 'yuubinkyoku', meaning: 'Kantor pos', category: 'places' },
    { jp: 'やっきょく', romaji: 'yakkyoku', meaning: 'Apotek', category: 'places' },
    { jp: 'えいがかん', romaji: 'eigakan', meaning: 'Bioskop', category: 'places' },
    { jp: 'びじゅつかん', romaji: 'bijutsukan', meaning: 'Museum seni', category: 'places' },
    { jp: 'はくぶつかん', romaji: 'hakubutsukan', meaning: 'Museum', category: 'places' },
    { jp: 'じんじゃ', romaji: 'jinja', meaning: 'Kuil Shinto', category: 'places' },
    { jp: 'おてら', romaji: 'otera', meaning: 'Kuil Buddha', category: 'places' },
    { jp: 'きょうかい', romaji: 'kyoukai', meaning: 'Gereja', category: 'places' },
    { jp: 'くうこう', romaji: 'kuukou', meaning: 'Bandara', category: 'places' },
    { jp: 'ちかてつ', romaji: 'chikatetsu', meaning: 'Kereta bawah tanah', category: 'places' },
    { jp: 'こうばん', romaji: 'kouban', meaning: 'Pos polisi', category: 'places' },
    { jp: 'だいしかん', romaji: 'daishikan', meaning: 'Kedutaan besar', category: 'places' },
    { jp: 'じむしょ', romaji: 'jimusho', meaning: 'Kantor', category: 'places' },
    { jp: 'しやくしょ', romaji: 'shiyakusho', meaning: 'Balai kota', category: 'places' },
    { jp: 'こうじょう', romaji: 'koujou', meaning: 'Pabrik', category: 'places' },
    { jp: 'うりば', romaji: 'uriba', meaning: 'Tempat penjualan', category: 'places' },
    { jp: 'デパート', romaji: 'depaato', meaning: 'Mal / Department store', category: 'places' },
    { jp: 'プール', romaji: 'puuru', meaning: 'Kolam renang', category: 'places' },
    { jp: 'トイレ', romaji: 'toire', meaning: 'Toilet', category: 'places' },
    { jp: 'かいだん', romaji: 'kaidan', meaning: 'Tangga', category: 'places' },
    { jp: 'エレベーター', romaji: 'erebeetaa', meaning: 'Lift', category: 'places' },
    { jp: 'いりぐち', romaji: 'iriguchi', meaning: 'Pintu masuk', category: 'places' },
    { jp: 'でぐち', romaji: 'deguchi', meaning: 'Pintu keluar', category: 'places' },
    { jp: 'かど', romaji: 'kado', meaning: 'Sudut jalan', category: 'places' },
    { jp: 'しんごう', romaji: 'shingou', meaning: 'Lampu lalu lintas', category: 'places' },
    { jp: 'はし', romaji: 'hashi', meaning: 'Jembatan', category: 'places' },
    { jp: 'こうさてん', romaji: 'kousaten', meaning: 'Persimpangan', category: 'places' },
    { jp: 'じむしつ', romaji: 'jimushitsu', meaning: 'Ruang kantor', category: 'places' },
    { jp: 'かいぎしつ', romaji: 'kaigishitsu', meaning: 'Ruang rapat', category: 'places' },
    { jp: 'きょうしつ', romaji: 'kyoushitsu', meaning: 'Ruang kelas', category: 'places' },
    { jp: 'しょくどう', romaji: 'shokudou', meaning: 'Kantin', category: 'places' },
    { jp: 'ねだん', romaji: 'nedan', meaning: 'Harga', category: 'places' },
    { jp: 'はな', romaji: 'hana', meaning: 'Bunga', category: 'nature' },
    { jp: 'ひかり', romaji: 'hikari', meaning: 'Cahaya', category: 'nature' },
    { jp: 'そら', romaji: 'sora', meaning: 'Langit', category: 'nature' },
    { jp: 'うみ', romaji: 'umi', meaning: 'Laut', category: 'nature' },
    { jp: 'かわ', romaji: 'kawa', meaning: 'Sungai', category: 'nature' },
    { jp: 'やま', romaji: 'yama', meaning: 'Gunung', category: 'nature' },
    { jp: 'てんき', romaji: 'tenki', meaning: 'Cuaca', category: 'nature' },
    { jp: 'あめ', romaji: 'ame', meaning: 'Hujan', category: 'nature' },
    { jp: 'ゆき', romaji: 'yuki', meaning: 'Salju', category: 'nature' },
    { jp: 'かぜ', romaji: 'kaze', meaning: 'Angin', category: 'nature' },
    { jp: 'き', romaji: 'ki', meaning: 'Pohon', category: 'nature' },
    { jp: 'ほし', romaji: 'hoshi', meaning: 'Bintang', category: 'nature' },
    { jp: 'たいよう', romaji: 'taiyou', meaning: 'Matahari', category: 'nature' },
    { jp: 'くも', romaji: 'kumo', meaning: 'Awan', category: 'nature' },
    { jp: 'かみなり', romaji: 'kaminari', meaning: 'Petir', category: 'nature' },
    { jp: 'むし', romaji: 'mushi', meaning: 'Serangga', category: 'nature' },
    { jp: 'は', romaji: 'ha', meaning: 'Daun', category: 'nature' },
    { jp: 'くさ', romaji: 'kusa', meaning: 'Rumput', category: 'nature' },
    { jp: 'いし', romaji: 'ishi', meaning: 'Batu', category: 'nature' },
    { jp: 'すな', romaji: 'suna', meaning: 'Pasir', category: 'nature' },
    { jp: 'みずうみ', romaji: 'mizuumi', meaning: 'Danau', category: 'nature' },
    { jp: 'しま', romaji: 'shima', meaning: 'Pulau', category: 'nature' },
    { jp: 'もり', romaji: 'mori', meaning: 'Hutan', category: 'nature' },
    { jp: 'たいふう', romaji: 'taifuu', meaning: 'Topan', category: 'nature' },
    { jp: 'じしん', romaji: 'jishin', meaning: 'Gempa bumi', category: 'nature' },
    { jp: 'くもり', romaji: 'kumori', meaning: 'Berawan', category: 'nature' },
    { jp: 'はれ', romaji: 'hare', meaning: 'Cerah', category: 'nature' },
    { jp: 'くうき', romaji: 'kuuki', meaning: 'Udara', category: 'nature' },
    { jp: 'ねこ', romaji: 'neko', meaning: 'Kucing', category: 'animals' },
    { jp: 'いぬ', romaji: 'inu', meaning: 'Anjing', category: 'animals' },
    { jp: 'とり', romaji: 'tori', meaning: 'Burung', category: 'animals' },
    { jp: 'うま', romaji: 'uma', meaning: 'Kuda', category: 'animals' },
    { jp: 'うし', romaji: 'ushi', meaning: 'Sapi', category: 'animals' },
    { jp: 'ぶた', romaji: 'buta', meaning: 'Babi', category: 'animals' },
    { jp: 'ひつじ', romaji: 'hitsuji', meaning: 'Domba', category: 'animals' },
    { jp: 'さる', romaji: 'saru', meaning: 'Monyet', category: 'animals' },
    { jp: 'ぞう', romaji: 'zou', meaning: 'Gajah', category: 'animals' },
    { jp: 'らいおん', romaji: 'raion', meaning: 'Singa', category: 'animals' },
    { jp: 'とら', romaji: 'tora', meaning: 'Harimau', category: 'animals' },
    { jp: 'うさぎ', romaji: 'usagi', meaning: 'Kelinci', category: 'animals' },
    { jp: 'ねずみ', romaji: 'nezumi', meaning: 'Tikus', category: 'animals' },
    { jp: 'かめ', romaji: 'kame', meaning: 'Kura-kura', category: 'animals' },
    { jp: 'へび', romaji: 'hebi', meaning: 'Ular', category: 'animals' },
    { jp: 'ちょう', romaji: 'chou', meaning: 'Kupu-kupu', category: 'animals' },
    { jp: 'あたま', romaji: 'atama', meaning: 'Kepala', category: 'body' },
    { jp: 'かお', romaji: 'kao', meaning: 'Wajah', category: 'body' },
    { jp: 'め', romaji: 'me', meaning: 'Mata', category: 'body' },
    { jp: 'みみ', romaji: 'mimi', meaning: 'Telinga', category: 'body' },
    { jp: 'くち', romaji: 'kuchi', meaning: 'Mulut', category: 'body' },
    { jp: 'くび', romaji: 'kubi', meaning: 'Leher', category: 'body' },
    { jp: 'かた', romaji: 'kata', meaning: 'Bahu', category: 'body' },
    { jp: 'うで', romaji: 'ude', meaning: 'Lengan', category: 'body' },
    { jp: 'て', romaji: 'te', meaning: 'Tangan', category: 'body' },
    { jp: 'ゆび', romaji: 'yubi', meaning: 'Jari', category: 'body' },
    { jp: 'おなか', romaji: 'onaka', meaning: 'Perut', category: 'body' },
    { jp: 'せなか', romaji: 'senaka', meaning: 'Punggung', category: 'body' },
    { jp: 'あし', romaji: 'ashi', meaning: 'Kaki', category: 'body' },
    { jp: 'ひざ', romaji: 'hiza', meaning: 'Lutut', category: 'body' },
    { jp: 'かみ', romaji: 'kami', meaning: 'Rambut', category: 'body' },
    { jp: 'こえ', romaji: 'koe', meaning: 'Suara', category: 'body' },
    { jp: 'からだ', romaji: 'karada', meaning: 'Tubuh', category: 'body' },
    { jp: 'こころ', romaji: 'kokoro', meaning: 'Hati / Perasaan', category: 'body' },
    { jp: 'なみだ', romaji: 'namida', meaning: 'Air mata', category: 'body' },
    { jp: 'びょうき', romaji: 'byouki', meaning: 'Sakit / Penyakit', category: 'body' },
    { jp: 'くすり', romaji: 'kusuri', meaning: 'Obat', category: 'body' },
    { jp: 'ねつ', romaji: 'netsu', meaning: 'Demam', category: 'body' },
    { jp: 'ようふく', romaji: 'youfuku', meaning: 'Pakaian (gaya barat)', category: 'clothing' },
    { jp: 'シャツ', romaji: 'shatsu', meaning: 'Baju', category: 'clothing' },
    { jp: 'ズボン', romaji: 'zubon', meaning: 'Celana', category: 'clothing' },
    { jp: 'スカート', romaji: 'sukaato', meaning: 'Rok', category: 'clothing' },
    { jp: 'ブーツ', romaji: 'buutsu', meaning: 'Sepatu boot', category: 'clothing' },
    { jp: 'ソックス', romaji: 'sokkusu', meaning: 'Kaos kaki', category: 'clothing' },
    { jp: 'くつ', romaji: 'kutsu', meaning: 'Sepatu', category: 'clothing' },
    { jp: 'くつした', romaji: 'kutsushita', meaning: 'Kaos kaki (jp)', category: 'clothing' },
    { jp: 'ぼうし', romaji: 'boushi', meaning: 'Topi', category: 'clothing' },
    { jp: 'めがね', romaji: 'megane', meaning: 'Kacamata', category: 'clothing' },
    { jp: 'とけい', romaji: 'tokei', meaning: 'Jam tangan', category: 'clothing' },
    { jp: 'かばん', romaji: 'kaban', meaning: 'Tas', category: 'clothing' },
    { jp: 'さいふ', romaji: 'saifu', meaning: 'Dompet', category: 'clothing' },
    { jp: 'きもの', romaji: 'kimono', meaning: 'Kimono', category: 'clothing' },
    { jp: 'セーター', romaji: 'seetaa', meaning: 'Sweater', category: 'clothing' },
    { jp: 'コート', romaji: 'kooto', meaning: 'Mantel', category: 'clothing' },
    { jp: 'ネクタイ', romaji: 'nekutai', meaning: 'Dasi', category: 'clothing' },
    { jp: 'てぶくろ', romaji: 'tebukuro', meaning: 'Sarung tangan', category: 'clothing' },
    { jp: 'かさ', romaji: 'kasa', meaning: 'Payung', category: 'clothing' },
    { jp: 'ゆびわ', romaji: 'yubiwa', meaning: 'Cincin', category: 'clothing' },
    { jp: 'べんきょう', romaji: 'benkyou', meaning: 'Belajar (kata benda)', category: 'school' },
    { jp: 'しゅくだい', romaji: 'shukudai', meaning: 'PR / Tugas', category: 'school' },
    { jp: 'しけん', romaji: 'shiken', meaning: 'Ujian', category: 'school' },
    { jp: 'テスト', romaji: 'tesuto', meaning: 'Tes', category: 'school' },
    { jp: 'じゅぎょう', romaji: 'jugyou', meaning: 'Pelajaran', category: 'school' },
    { jp: 'せいと', romaji: 'seito', meaning: 'Siswa', category: 'school' },
    { jp: 'こうちょう', romaji: 'kouchou', meaning: 'Kepala sekolah', category: 'school' },
    { jp: 'にほんご', romaji: 'nihongo', meaning: 'Bahasa Jepang', category: 'school' },
    { jp: 'えいご', romaji: 'eigo', meaning: 'Bahasa Inggris', category: 'school' },
    { jp: 'すうがく', romaji: 'suugaku', meaning: 'Matematika', category: 'school' },
    { jp: 'かがく', romaji: 'kagaku', meaning: 'Ilmu pengetahuan', category: 'school' },
    { jp: 'れきし', romaji: 'rekishi', meaning: 'Sejarah', category: 'school' },
    { jp: 'たいいく', romaji: 'taiiku', meaning: 'Olahraga (pelajaran)', category: 'school' },
    { jp: 'おんがく', romaji: 'ongaku', meaning: 'Musik', category: 'school' },
    { jp: 'びじゅつ', romaji: 'bijutsu', meaning: 'Seni rupa', category: 'school' },
    { jp: 'けいざい', romaji: 'keizai', meaning: 'Ekonomi', category: 'school' },
    { jp: 'えんぴつ', romaji: 'enpitsu', meaning: 'Pensil', category: 'school' },
    { jp: 'けしごむ', romaji: 'keshigomu', meaning: 'Penghapus', category: 'school' },
    { jp: 'じょうぎ', romaji: 'jougi', meaning: 'Penggaris', category: 'school' },
    { jp: 'こくばん', romaji: 'kokuban', meaning: 'Papan tulis', category: 'school' },
    { jp: 'つくえ', romaji: 'tsukue', meaning: 'Meja belajar', category: 'school' },
    { jp: 'いす', romaji: 'isu', meaning: 'Kursi', category: 'school' },
    { jp: 'きょうかしょ', romaji: 'kyoukasho', meaning: 'Buku pelajaran', category: 'school' },
    { jp: 'としょ', romaji: 'tosho', meaning: 'Buku (koleksi)', category: 'school' },
    { jp: 'そつぎょう', romaji: 'sotsugyou', meaning: 'Kelulusan', category: 'school' },
    { jp: 'にゅうがく', romaji: 'nyuugaku', meaning: 'Masuk sekolah', category: 'school' },
    { jp: 'がっき', romaji: 'gakki', meaning: 'Semester', category: 'school' },
    { jp: 'せんもん', romaji: 'senmon', meaning: 'Jurusan / Spesialisasi', category: 'school' },
    { jp: 'いえ', romaji: 'ie', meaning: 'Rumah', category: 'house' },
    { jp: 'にわ', romaji: 'niwa', meaning: 'Halaman / Taman rumah', category: 'house' },
    { jp: 'だいどころ', romaji: 'daidokoro', meaning: 'Dapur', category: 'house' },
    { jp: 'おふろ', romaji: 'ofuro', meaning: 'Kamar mandi (bak)', category: 'house' },
    { jp: 'げんかん', romaji: 'genkan', meaning: 'Teras depan rumah', category: 'house' },
    { jp: 'まど', romaji: 'mado', meaning: 'Jendela', category: 'house' },
    { jp: 'ドア', romaji: 'doa', meaning: 'Pintu', category: 'house' },
    { jp: 'かべ', romaji: 'kabe', meaning: 'Dinding', category: 'house' },
    { jp: 'ゆか', romaji: 'yuka', meaning: 'Lantai', category: 'house' },
    { jp: 'てんじょう', romaji: 'tenjou', meaning: 'Langit-langit', category: 'house' },
    { jp: 'ベッド', romaji: 'beddo', meaning: 'Tempat tidur', category: 'house' },
    { jp: 'テーブル', romaji: 'teeburu', meaning: 'Meja', category: 'house' },
    { jp: 'チェア', romaji: 'chea', meaning: 'Kursi (loanword)', category: 'house' },
    { jp: 'たな', romaji: 'tana', meaning: 'Rak', category: 'house' },
    { jp: 'れいぞうこ', romaji: 'reizouko', meaning: 'Kulkas', category: 'house' },
    { jp: 'でんき', romaji: 'denki', meaning: 'Listrik / Lampu', category: 'house' },
    { jp: 'でんわ', romaji: 'denwa', meaning: 'Telepon', category: 'house' },
    { jp: 'テレビ', romaji: 'terebi', meaning: 'Televisi', category: 'house' },
    { jp: 'ラジオ', romaji: 'rajio', meaning: 'Radio', category: 'house' },
    { jp: 'エアコン', romaji: 'eakon', meaning: 'AC', category: 'house' },
    { jp: 'せんぷうき', romaji: 'senpuuki', meaning: 'Kipas angin', category: 'house' },
    { jp: 'かがみ', romaji: 'kagami', meaning: 'Cermin', category: 'house' },
    { jp: 'かびん', romaji: 'kabin', meaning: 'Vas bunga', category: 'house' },
    { jp: 'ふとん', romaji: 'futon', meaning: 'Kasur lipat', category: 'house' },
    { jp: 'まくら', romaji: 'makura', meaning: 'Bantal', category: 'house' },
    { jp: 'もうふ', romaji: 'moufu', meaning: 'Selimut', category: 'house' },
    { jp: 'せっけん', romaji: 'sekken', meaning: 'Sabun', category: 'house' },
    { jp: 'タオル', romaji: 'taoru', meaning: 'Handuk', category: 'house' },
    { jp: 'はぶらし', romaji: 'haburashi', meaning: 'Sikat gigi', category: 'house' },
    { jp: 'はさみ', romaji: 'hasami', meaning: 'Gunting', category: 'house' },
    { jp: 'でんしゃ', romaji: 'densha', meaning: 'Kereta', category: 'transportation' },
    { jp: 'じどうしゃ', romaji: 'jidousha', meaning: 'Mobil', category: 'transportation' },
    { jp: 'くるま', romaji: 'kuruma', meaning: 'Mobil', category: 'transportation' },
    { jp: 'じてんしゃ', romaji: 'jitensha', meaning: 'Sepeda', category: 'transportation' },
    { jp: 'ひこうき', romaji: 'hikouki', meaning: 'Pesawat terbang', category: 'transportation' },
    { jp: 'ふね', romaji: 'fune', meaning: 'Kapal', category: 'transportation' },
    { jp: 'バス', romaji: 'basu', meaning: 'Bus', category: 'transportation' },
    { jp: 'タクシー', romaji: 'takushii', meaning: 'Taksi', category: 'transportation' },
    { jp: 'しんかんせん', romaji: 'shinkansen', meaning: 'Kereta cepat Shinkansen', category: 'transportation' },
    { jp: 'オートバイ', romaji: 'ootobai', meaning: 'Motor', category: 'transportation' },
    { jp: 'バイク', romaji: 'baiku', meaning: 'Motor (singkat)', category: 'transportation' },
    { jp: 'きっぷ', romaji: 'kippu', meaning: 'Tiket', category: 'transportation' },
    { jp: 'のりば', romaji: 'noriba', meaning: 'Tempat naik kendaraan', category: 'transportation' },
    { jp: 'うんちん', romaji: 'unchin', meaning: 'Ongkos', category: 'transportation' },
    { jp: 'こうつう', romaji: 'koutsuu', meaning: 'Lalu lintas', category: 'transportation' },
    { jp: 'みち', romaji: 'michi', meaning: 'Jalan', category: 'transportation' },
    { jp: 'どうろ', romaji: 'douro', meaning: 'Jalan raya', category: 'transportation' },
    { jp: 'うえ', romaji: 'ue', meaning: 'Atas', category: 'directions' },
    { jp: 'した', romaji: 'shita', meaning: 'Bawah', category: 'directions' },
    { jp: 'なか', romaji: 'naka', meaning: 'Dalam', category: 'directions' },
    { jp: 'そと', romaji: 'soto', meaning: 'Luar', category: 'directions' },
    { jp: 'うしろ', romaji: 'ushiro', meaning: 'Belakang', category: 'directions' },
    { jp: 'みぎ', romaji: 'migi', meaning: 'Kanan', category: 'directions' },
    { jp: 'ひだり', romaji: 'hidari', meaning: 'Kiri', category: 'directions' },
    { jp: 'となり', romaji: 'tonari', meaning: 'Sebelah', category: 'directions' },
    { jp: 'よこ', romaji: 'yoko', meaning: 'Samping', category: 'directions' },
    { jp: 'あいだ', romaji: 'aida', meaning: 'Antara', category: 'directions' },
    { jp: 'ちかく', romaji: 'chikaku', meaning: 'Dekat sini', category: 'directions' },
    { jp: 'むこう', romaji: 'mukou', meaning: 'Seberang / Sebelah sana', category: 'directions' },
    { jp: 'きた', romaji: 'kita', meaning: 'Utara', category: 'directions' },
    { jp: 'みなみ', romaji: 'minami', meaning: 'Selatan', category: 'directions' },
    { jp: 'ひがし', romaji: 'higashi', meaning: 'Timur', category: 'directions' },
    { jp: 'にし', romaji: 'nishi', meaning: 'Barat', category: 'directions' },
    { jp: 'まわり', romaji: 'mawari', meaning: 'Sekeliling', category: 'directions' },
    { jp: 'すみ', romaji: 'sumi', meaning: 'Pojok', category: 'directions' },
    { jp: 'えいが', romaji: 'eiga', meaning: 'Film', category: 'hobbies' },
    { jp: 'しゃしん', romaji: 'shashin', meaning: 'Foto', category: 'hobbies' },
    { jp: 'りょこう', romaji: 'ryokou', meaning: 'Perjalanan wisata', category: 'hobbies' },
    { jp: 'どくしょ', romaji: 'dokusho', meaning: 'Membaca buku (hobi)', category: 'hobbies' },
    { jp: 'かいもの', romaji: 'kaimono', meaning: 'Berbelanja', category: 'hobbies' },
    { jp: 'さんぽ', romaji: 'sanpo', meaning: 'Jalan-jalan', category: 'hobbies' },
    { jp: 'つり', romaji: 'tsuri', meaning: 'Memancing', category: 'hobbies' },
    { jp: 'すいえい', romaji: 'suiei', meaning: 'Berenang (hobi)', category: 'hobbies' },
    { jp: 'やきゅう', romaji: 'yakyuu', meaning: 'Bisbol', category: 'hobbies' },
    { jp: 'サッカー', romaji: 'sakkaa', meaning: 'Sepak bola', category: 'hobbies' },
    { jp: 'テニス', romaji: 'tenisu', meaning: 'Tenis', category: 'hobbies' },
    { jp: 'スポーツ', romaji: 'supootsu', meaning: 'Olahraga', category: 'hobbies' },
    { jp: 'ゲーム', romaji: 'geemu', meaning: 'Game', category: 'hobbies' },
    { jp: 'ダンス', romaji: 'dansu', meaning: 'Dansa', category: 'hobbies' },
    { jp: 'りょうり', romaji: 'ryouri', meaning: 'Masakan', category: 'hobbies' },
    { jp: 'えを かく', romaji: 'e wo kaku', meaning: 'Menggambar', category: 'hobbies' },
    { jp: 'キャンプ', romaji: 'kyanpu', meaning: 'Berkemah', category: 'hobbies' },
    { jp: 'ピアノ', romaji: 'piano', meaning: 'Piano', category: 'hobbies' },
    { jp: 'インターネット', romaji: 'intaanetto', meaning: 'Internet', category: 'katakana' },
    { jp: 'コンピュータ', romaji: 'konpyuuta', meaning: 'Komputer', category: 'katakana' },
    { jp: 'スマートフォン', romaji: 'sumaatofoon', meaning: 'Smartphone', category: 'katakana' },
    { jp: 'カメラ', romaji: 'kamera', meaning: 'Kamera', category: 'katakana' },
    { jp: 'ノート', romaji: 'nooto', meaning: 'Buku catatan', category: 'katakana' },
    { jp: 'ペン', romaji: 'pen', meaning: 'Pulpen', category: 'katakana' },
    { jp: 'カップ', romaji: 'kappu', meaning: 'Cangkir', category: 'katakana' },
    { jp: 'スプーン', romaji: 'supuun', meaning: 'Sendok', category: 'katakana' },
    { jp: 'フォーク', romaji: 'fooku', meaning: 'Garpu', category: 'katakana' },
    { jp: 'ナイフ', romaji: 'naifu', meaning: 'Pisau', category: 'katakana' },
    { jp: 'プレゼント', romaji: 'purezento', meaning: 'Hadiah', category: 'katakana' },
    { jp: 'パーティー', romaji: 'paatii', meaning: 'Pesta', category: 'katakana' },
    { jp: 'ミュージック', romaji: 'myuujikku', meaning: 'Musik (loanword)', category: 'katakana' },
    { jp: 'アニメ', romaji: 'anime', meaning: 'Anime', category: 'katakana' },
    { jp: 'バッグ', romaji: 'baggu', meaning: 'Tas (loanword)', category: 'katakana' },
    { jp: 'メニュー', romaji: 'menyuu', meaning: 'Menu', category: 'katakana' },
    { jp: 'チケット', romaji: 'chiketto', meaning: 'Tiket (loanword)', category: 'katakana' },
    { jp: 'パスポート', romaji: 'pasupooto', meaning: 'Paspor', category: 'katakana' },
    { jp: 'ホームページ', romaji: 'hoomupeeji', meaning: 'Halaman web', category: 'katakana' },
    { jp: 'メール', romaji: 'meeru', meaning: 'Email', category: 'katakana' },
    { jp: 'アルバイト', romaji: 'arubaito', meaning: 'Kerja paruh waktu', category: 'katakana' },
    { jp: 'トイレット', romaji: 'toiretto', meaning: 'Toilet (loanword)', category: 'katakana' },
    { jp: 'シャワー', romaji: 'shawaa', meaning: 'Shower', category: 'katakana' },
    { jp: 'クラス', romaji: 'kurasu', meaning: 'Kelas', category: 'katakana' },
    { jp: 'ページ', romaji: 'peeji', meaning: 'Halaman', category: 'katakana' },
    { jp: 'サイズ', romaji: 'saizu', meaning: 'Ukuran', category: 'katakana' },
    { jp: 'カード', romaji: 'kaado', meaning: 'Kartu', category: 'katakana' },
    { jp: 'ポケット', romaji: 'poketto', meaning: 'Kantong', category: 'katakana' },
    { jp: 'パソコン', romaji: 'pasokon', meaning: 'Komputer pribadi', category: 'katakana' },
    { jp: 'スマホ', romaji: 'sumaho', meaning: 'HP / Ponsel pintar', category: 'katakana' }
];

const kanji = [
    { jp: '魚', romaji: 'sakana', meaning: 'Ikan', category: 'makanan' },
    { jp: '肉', romaji: 'niku', meaning: 'Daging', category: 'makanan' },
    { jp: '卵', romaji: 'tamago', meaning: 'Telur', category: 'makanan' },
    { jp: '水', romaji: 'mizu', meaning: 'Air', category: 'makanan' },
    { jp: '食べます', romaji: 'tabemasu', meaning: 'Makan', category: 'kata_kerja' },
    { jp: '飲みます', romaji: 'nomimasu', meaning: 'Minum', category: 'kata_kerja' },
    { jp: '新しい', romaji: 'atarashii', meaning: 'Baru', category: 'sifat' },
    { jp: '古い', romaji: 'furui', meaning: 'Lama / Tua', category: 'sifat' },
    { jp: '大きい', romaji: 'ookii', meaning: 'Besar', category: 'sifat' },
    { jp: '小さい', romaji: 'chiisai', meaning: 'Kecil', category: 'sifat' },
    { jp: '時', romaji: ['ji', 'toki'], meaning: 'Jam (waktu)', category: 'waktu' },
    { jp: '分', romaji: ['fun', 'pun'], meaning: 'Menit', category: 'waktu' },
    { jp: '半', romaji: 'han', meaning: 'Setengah', category: 'waktu' },
    { jp: '月曜日', romaji: 'getsuyoubi', meaning: 'Senin', category: 'waktu' },
    { jp: '火曜日', romaji: 'kayoubi', meaning: 'Selasa', category: 'waktu' },
    { jp: '水曜日', romaji: 'suiyoubi', meaning: 'Rabu', category: 'waktu' },
    { jp: '木曜日', romaji: 'mokuyoubi', meaning: 'Kamis', category: 'waktu' },
    { jp: '金曜日', romaji: 'kinyoubi', meaning: 'Jumat', category: 'waktu' },
    { jp: '土曜日', romaji: 'doyoubi', meaning: 'Sabtu', category: 'waktu' },
    { jp: '日曜日', romaji: 'nichiyoubi', meaning: 'Minggu', category: 'waktu' },
    { jp: '言います', romaji: 'iimasu', meaning: 'Mengatakan', category: 'kata_kerja' },
    { jp: '話します', romaji: 'hanashimasu', meaning: 'Berbicara', category: 'kata_kerja' },
    { jp: '読みます', romaji: 'yomimasu', meaning: 'Membaca', category: 'kata_kerja' },
    { jp: '見ます', romaji: 'mimasu', meaning: 'Melihat', category: 'kata_kerja' },
    { jp: '聞きます', romaji: 'kikimasu', meaning: 'Mendengar / Bertanya', category: 'kata_kerja' },
    { jp: '書きます', romaji: 'kakimasu', meaning: 'Menulis', category: 'kata_kerja' },
    { jp: '一', romaji: 'ichi', meaning: 'Satu', category: 'angka' },
    { jp: '二', romaji: 'ni', meaning: 'Dua', category: 'angka' },
    { jp: '三', romaji: 'san', meaning: 'Tiga', category: 'angka' },
    { jp: '四', romaji: ['yon', 'shi'], meaning: 'Empat', category: 'angka' },
    { jp: '五', romaji: 'go', meaning: 'Lima', category: 'angka' },
    { jp: '六', romaji: 'roku', meaning: 'Enam', category: 'angka' },
    { jp: '七', romaji: ['nana', 'shichi'], meaning: 'Tujuh', category: 'angka' },
    { jp: '八', romaji: 'hachi', meaning: 'Delapan', category: 'angka' },
    { jp: '九', romaji: ['kyuu', 'ku'], meaning: 'Sembilan', category: 'angka' },
    { jp: '十', romaji: ['juu', 'too'], meaning: 'Sepuluh', category: 'angka' },
    { jp: '年', romaji: ['nen', 'toshi'], meaning: 'Tahun', category: 'waktu' },
    { jp: '日', romaji: ['nichi', 'hi'], meaning: 'Hari / Tanggal', category: 'waktu' },
    { jp: '月', romaji: ['gatsu', 'tsuki'], meaning: 'Bulan', category: 'waktu' },
    { jp: '東', romaji: 'higashi', meaning: 'Timur', category: 'arah' },
    { jp: '西', romaji: 'nishi', meaning: 'Barat', category: 'arah' },
    { jp: '南', romaji: 'minami', meaning: 'Selatan', category: 'arah' },
    { jp: '北', romaji: 'kita', meaning: 'Utara', category: 'arah' },
    { jp: '口', romaji: 'kuchi', meaning: 'Mulut / Pintu', category: 'arah' },
    { jp: '東口', romaji: 'higashiguchi', meaning: 'Pintu keluar timur', category: 'arah' },
    { jp: '西口', romaji: 'nishiguchi', meaning: 'Pintu keluar barat', category: 'arah' },
    { jp: '南口', romaji: 'minamiguchi', meaning: 'Pintu keluar selatan', category: 'arah' },
    { jp: '北口', romaji: 'kitaguchi', meaning: 'Pintu keluar utara', category: 'arah' },
    { jp: 'お金', romaji: 'okane', meaning: 'Uang', category: 'uang' },
    { jp: '円', romaji: 'en', meaning: 'Yen', category: 'uang' },
    { jp: '百', romaji: 'hyaku', meaning: 'Seratus', category: 'angka' },
    { jp: '千', romaji: 'sen', meaning: 'Seribu', category: 'angka' },
    { jp: '万', romaji: 'man', meaning: 'Sepuluh ribu', category: 'angka' },
    { jp: '百円', romaji: 'hyakuen', meaning: '100 Yen', category: 'uang' },
    { jp: '千円', romaji: 'senen', meaning: '1000 Yen', category: 'uang' },
    { jp: '一万円', romaji: 'ichimanen', meaning: '10.000 Yen', category: 'uang' },
    { jp: '買います', romaji: 'kaimasu', meaning: 'Membeli', category: 'kata_kerja' },
    { jp: '買い物', romaji: 'kaimono', meaning: 'Belanja', category: 'kata_kerja' },
    { jp: '行きます', romaji: 'ikimasu', meaning: 'Pergi', category: 'kata_kerja' },
    { jp: '来ます', romaji: 'kimasu', meaning: 'Datang', category: 'kata_kerja' },
    { jp: '会います', romaji: 'aimasu', meaning: 'Bertemu', category: 'kata_kerja' },
    { jp: '休みます', romaji: 'yasumimasu', meaning: 'Istirahat / Libur', category: 'kata_kerja' },
    { jp: '日本', romaji: ['nihon', 'nippon'], meaning: 'Jepang', category: 'negara' },
    { jp: '東京', romaji: 'toukyou', meaning: 'Tokyo', category: 'negara' },
    { jp: '私', romaji: ['watashi', 'watakushi'], meaning: 'Saya', category: 'orang' },
    { jp: '父', romaji: 'chichi', meaning: 'Ayah (saya)', category: 'orang' },
    { jp: '母', romaji: 'haha', meaning: 'Ibu (saya)', category: 'orang' },
    { jp: '子供', romaji: 'kodomo', meaning: 'Anak', category: 'orang' },
    { jp: '男', romaji: 'otoko', meaning: 'Laki-laki', category: 'orang' },
    { jp: '女', romaji: 'onna', meaning: 'Perempuan', category: 'orang' },
    { jp: '人', romaji: ['hito', 'nin', 'jin'], meaning: 'Orang', category: 'orang' },
    { jp: 'お父さん', romaji: 'otousan', meaning: 'Ayah (orang lain)', category: 'orang' },
    { jp: 'お母さん', romaji: 'okaasan', meaning: 'Ibu (orang lain)', category: 'orang' },
    { jp: '国', romaji: 'kuni', meaning: 'Negara', category: 'negara' },
    { jp: '外国', romaji: 'gaikoku', meaning: 'Luar negeri', category: 'negara' },
    { jp: '何人', romaji: ['nanijin', 'nannin'], meaning: 'Orang mana (kebangsaan) / Berapa orang', category: 'negara' },
    { jp: '語', romaji: 'go', meaning: 'Bahasa (akhiran)', category: 'bahasa' },
    { jp: '日本語', romaji: 'nihongo', meaning: 'Bahasa Jepang', category: 'bahasa' },
    { jp: '英語', romaji: 'eigo', meaning: 'Bahasa Inggris', category: 'bahasa' },
    { jp: '中国語', romaji: 'chuugokugo', meaning: 'Bahasa Mandarin', category: 'bahasa' },
    { jp: '日本人', romaji: 'nihonjin', meaning: 'Orang Jepang', category: 'negara' },
    { jp: '何', romaji: ['nani', 'nan'], meaning: 'Apa', category: 'basic' },
    { jp: '好き', romaji: 'suki', meaning: 'Suka', category: 'sifat' },
    { jp: '本', romaji: 'hon', meaning: 'Buku', category: 'basic' },
    { jp: '読書', romaji: 'dokusho', meaning: 'Membaca buku', category: 'kata_kerja' },
    { jp: '春', romaji: 'haru', meaning: 'Musim semi', category: 'musim' },
    { jp: '秋', romaji: 'aki', meaning: 'Musim gugur', category: 'musim' },
    { jp: '夏', romaji: 'natsu', meaning: 'Musim panas', category: 'musim' },
    { jp: '冬', romaji: 'fuyu', meaning: 'Musim dingin', category: 'musim' },
    { jp: '今', romaji: 'ima', meaning: 'Sekarang', category: 'waktu' },
    { jp: '今日', romaji: 'kyou', meaning: 'Hari ini', category: 'waktu' },
    { jp: '花', romaji: 'hana', meaning: 'Bunga', category: 'alam' },
    { jp: '海', romaji: 'umi', meaning: 'Laut', category: 'alam' },
    { jp: '山', romaji: 'yama', meaning: 'Gunung', category: 'alam' },
    { jp: '川', romaji: 'kawa', meaning: 'Sungai', category: 'alam' },
    { jp: '雨', romaji: 'ame', meaning: 'Hujan', category: 'alam' },
    { jp: '雪', romaji: 'yuki', meaning: 'Salju', category: 'alam' },
    { jp: '天気', romaji: 'tenki', meaning: 'Cuaca', category: 'alam' },
    { jp: '晴れ', romaji: 'hare', meaning: 'Cerah', category: 'alam' },
    { jp: '雲', romaji: 'kumo', meaning: 'Awan', category: 'alam' },
    { jp: '空', romaji: 'sora', meaning: 'Langit / Udara', category: 'alam' },
    { jp: '風', romaji: 'kaze', meaning: 'Angin', category: 'alam' },
    { jp: '町', romaji: 'machi', meaning: 'Kota / Kota kecil', category: 'tempat' },
    { jp: '人気', romaji: 'ninki', meaning: 'Populer / Terkenal', category: 'sifat' },
    { jp: '店', romaji: 'mise', meaning: 'Toko / Warung', category: 'tempat' },
    { jp: '多い', romaji: 'ooi', meaning: 'Banyak', category: 'sifat' },
    { jp: '少ない', romaji: 'sukunai', meaning: 'Sedikit', category: 'sifat' },
    { jp: '高い', romaji: 'takai', meaning: 'Mahal / Tinggi', category: 'sifat' },
    { jp: '安い', romaji: 'yasui', meaning: 'Murah', category: 'sifat' },
    { jp: '広い', romaji: 'hiroi', meaning: 'Luas / Lebar', category: 'sifat' },
    { jp: '道', romaji: 'michi', meaning: 'Jalan / Jalur', category: 'tempat' },
    { jp: '通り', romaji: 'toori', meaning: 'Jalan raya / Penyeberangan', category: 'tempat' },
    { jp: '右', romaji: 'migi', meaning: 'Kanan', category: 'arah' },
    { jp: '左', romaji: 'hidari', meaning: 'Kiri', category: 'arah' },
    { jp: '一つ', romaji: 'hitotsu', meaning: 'Satu buah / Satu hal', category: 'angka' },
    { jp: '二つ', romaji: 'futatsu', meaning: 'Dua buah / Dua hal', category: 'angka' },
    { jp: '赤い', romaji: 'akai', meaning: 'Merah', category: 'warna' },
    { jp: '青い', romaji: 'aoi', meaning: 'Biru / Hijau muda', category: 'warna' },
    { jp: '黒い', romaji: 'kuroi', meaning: 'Hitam', category: 'warna' },
    { jp: '白い', romaji: 'shiroi', meaning: 'Putih', category: 'warna' },
    { jp: '日', romaji: 'hi / nichi', meaning: 'Hari / Matahari', category: 'waktu' },
    { jp: '時間', romaji: 'jikan', meaning: 'Waktu / Jam (durasi)', category: 'waktu' },
    { jp: '場所', romaji: 'basho', meaning: 'Tempat / Lokasi', category: 'tempat' },
    { jp: '駅', romaji: 'eki', meaning: 'Stasiun', category: 'tempat' },
    { jp: '出かけます', romaji: 'dekake masu', meaning: 'Pergi keluar / Berangkat', category: 'kata kerja' },
    { jp: '待ちます', romaji: 'machi masu', meaning: 'Menunggu', category: 'kata kerja' },
    { jp: '止まります', romaji: 'tomari masu', meaning: 'Berhenti / Menginap', category: 'kata kerja' },
    { jp: '食事', romaji: 'shokuji', meaning: 'Makan / Hidangan', category: 'kegiatan' },
    { jp: '仕事', romaji: 'shigoto', meaning: 'Pekerjaan / Tugas', category: 'kegiatan' },
    { jp: '前', romaji: 'mae', meaning: 'Sebelum / Depan', category: 'waktu_arah' },
    { jp: '後', romaji: 'ato / ushiro', meaning: 'Setelah / Belakang', category: 'waktu_arah' },
    { jp: '朝', romaji: 'asa', meaning: 'Pagi', category: 'waktu' },
    { jp: '昼', romaji: 'hiru', meaning: 'Siang', category: 'waktu' },
    { jp: '夜', romaji: 'yoru', meaning: 'Malam', category: 'waktu' },
    { jp: '乗ります', romaji: 'nori masu', meaning: 'Naik (kendaraan)', category: 'kata kerja' },
    { jp: '学校', romaji: 'gakkou', meaning: 'Sekolah', category: 'pendidikan' },
    { jp: '小学校', romaji: 'shougangkou', meaning: 'Sekolah Dasar (SD)', category: 'pendidikan' },
    { jp: '中学校', romaji: 'chuugakkou', meaning: 'Sekolah Menengah Pertama (SMP)', category: 'pendidikan' },
    { jp: '高校', romaji: 'koukou', meaning: 'Sekolah Menengah Atas (SMA)', category: 'pendidikan' },
    { jp: '大学', romaji: 'daigaku', meaning: 'Universitas / Perguruan Tinggi', category: 'pendidikan' },
    { jp: '先生', romaji: 'sensei', meaning: 'Guru / Dosen / Dokter', category: 'manusia' },
    { jp: '学生', romaji: 'gakusei', meaning: 'Siswa / Mahasiswa', category: 'manusia' },
    { jp: '年生', romaji: 'nensei', meaning: 'Tingkat kelas / Tahun angkatan', category: 'pendidikan' },
    { jp: '勉強', romaji: 'benkyou', meaning: 'Belajar', category: 'kegiatan' },
    { jp: '文化', romaji: 'bunka', meaning: 'Budaya / Kebudayaan', category: 'sosial' },
    { jp: '音楽', romaji: 'ongaku', meaning: 'Musik', category: 'hiburan' },
    { jp: '旅行', romaji: 'ryokou', meaning: 'Piknik / Perjalanan wisata', category: 'kegiatan' },
    { jp: '留学', romaji: 'ryuugaku', meaning: 'Belajar di luar negeri / Studi banding', category: 'pendidikan' },
    { jp: '友達', romaji: 'tomodachi', meaning: 'Teman / Sahabat', category: 'manusia' },
    { jp: '楽しい', romaji: 'tanoshii', meaning: 'Menyenangkan / Gembira', category: 'sifat' },
    { jp: '週', romaji: 'shuu', meaning: 'Minggu (satuan waktu)', category: 'waktu' },
    { jp: '回', romaji: 'kai', meaning: 'Kali (frekuensi / ronde)', category: 'angka' },
    { jp: '食べ物', romaji: 'tabemono', meaning: 'Makanan', category: 'makanan' },
    { jp: '飲み物', romaji: 'nomimono', meaning: 'Minuman', category: 'makanan' },
    { jp: 'お茶', romaji: 'ocha', meaning: 'Teh / Teh hijau Jepang', category: 'makanan' },
    { jp: 'お酒', romaji: 'osake', meaning: 'Alkohol / Sake Jepang', category: 'makanan' },
    { jp: '持っていきます', romaji: 'motte iki masu', meaning: 'Membawa (pergi)', category: 'kata kerja' },
    { jp: '作ります', romaji: 'tsukuri masu', meaning: 'Membuat / Memproduksi', category: 'kata kerja' },
    { jp: 'お願いします', romaji: 'onegai shimasu', meaning: 'Tolong / Mohon bantuannya', category: 'ungkapan' }
];
