const hiragana_dasar = [
    { char: 'あ', romaji: 'a', strokes: 'Mulai dari kiri ke kanan, kemudian dari atas ke bawah' },
    { char: 'い', romaji: 'i', strokes: 'Dua garis vertikal dari atas ke bawah' },
    { char: 'う', romaji: 'u', strokes: 'Garis horizontal, lalu lengkungan dari kiri bawah' },
    { char: 'え', romaji: 'e', strokes: 'Garis horizontal atas, lalu vertikal, lalu horizontal bawah' },
    { char: 'お', romaji: 'o', strokes: 'Dari atas kiri melengkung ke bawah dan kanan' },
    { char: 'か', romaji: 'ka', strokes: 'Tiga goresan: horizontal, vertikal, diagonal' },
    { char: 'き', romaji: 'ki', strokes: 'Tiga garis horizontal, satu garis vertikal' },
    { char: 'く', romaji: 'ku', strokes: 'Satu goresan melengkung dari atas ke bawah kanan' },
    { char: 'け', romaji: 'ke', strokes: 'Tiga goresan: diagonal, horizontal, vertikal' },
    { char: 'こ', romaji: 'ko', strokes: 'Dua garis horizontal' },
    { char: 'さ', romaji: 'sa', strokes: 'Tiga goresan: horizontal, vertikal melengkung, horizontal' },
    { char: 'し', romaji: 'shi', strokes: 'Satu goresan lengkungan dari atas ke bawah' },
    { char: 'す', romaji: 'su', strokes: 'Dua goresan melengkung' },
    { char: 'せ', romaji: 'se', strokes: 'Tiga goresan: horizontal, lengkungan, horizontal' },
    { char: 'そ', romaji: 'so', strokes: 'Dua goresan: horizontal melengkung, lengkungan besar' },
    { char: 'た', romaji: 'ta', strokes: 'Tiga goresan: horizontal, vertikal, lengkungan' },
    { char: 'ち', romaji: 'chi', strokes: 'Dua goresan: horizontal, lengkungan panjang' },
    { char: 'つ', romaji: 'tsu', strokes: 'Satu goresan melengkung horizontal' },
    { char: 'て', romaji: 'te', strokes: 'Satu goresan horizontal dengan ekor ke bawah' },
    { char: 'と', romaji: 'to', strokes: 'Dua goresan: vertikal, lengkungan' },
    { char: 'な', romaji: 'na', strokes: 'Empat goresan dari kiri ke kanan' },
    { char: 'に', romaji: 'ni', strokes: 'Tiga goresan: horizontal, horizontal, vertikal' },
    { char: 'ぬ', romaji: 'nu', strokes: 'Dua goresan melengkung dengan lingkaran' },
    { char: 'ね', romaji: 'ne', strokes: 'Tiga goresan dengan lengkungan besar' },
    { char: 'の', romaji: 'no', strokes: 'Satu goresan spiral' },
    { char: 'は', romaji: 'ha', strokes: 'Tiga goresan: vertikal, lengkungan, lingkaran' },
    { char: 'ひ', romaji: 'hi', strokes: 'Dua goresan: vertikal, horizontal dengan lengkungan' },
    { char: 'ふ', romaji: 'fu', strokes: 'Empat goresan membentuk huruf' },
    { char: 'へ', romaji: 'he', strokes: 'Satu goresan diagonal dari kiri atas ke kanan bawah' },
    { char: 'ほ', romaji: 'ho', strokes: 'Empat goresan: horizontal, vertikal, dua lengkungan' },
    { char: 'ま', romaji: 'ma', strokes: 'Tiga goresan: horizontal, vertikal, lengkungan' },
    { char: 'み', romaji: 'mi', strokes: 'Dua goresan melengkung' },
    { char: 'む', romaji: 'mu', strokes: 'Tiga goresan dengan lengkungan besar' },
    { char: 'め', romaji: 'me', strokes: 'Dua goresan membentuk angka 8' },
    { char: 'も', romaji: 'mo', strokes: 'Tiga goresan: horizontal, vertikal, lengkungan' },
    { char: 'や', romaji: 'ya', strokes: 'Tiga goresan membentuk huruf' },
    { char: 'ゆ', romaji: 'yu', strokes: 'Dua goresan melengkung' },
    { char: 'よ', romaji: 'yo', strokes: 'Dua goresan: horizontal, vertikal melengkung' },
    { char: 'ら', romaji: 'ra', strokes: 'Dua goresan: vertikal dengan lengkungan' },
    { char: 'り', romaji: 'ri', strokes: 'Dua goresan: vertikal, horizontal dengan lengkungan' },
    { char: 'る', romaji: 'ru', strokes: 'Dua goresan membentuk spiral kecil' },
    { char: 'れ', romaji: 're', strokes: 'Satu goresan melengkung dengan ekor' },
    { char: 'ろ', romaji: 'ro', strokes: 'Tiga goresan: horizontal, vertikal, lengkungan' },
    { char: 'わ', romaji: 'wa', strokes: 'Dua goresan melengkung' },
    { char: 'を', romaji: 'wo', strokes: 'Tiga goresan: horizontal, lengkungan, vertikal' },
    { char: 'ん', romaji: 'n', strokes: 'Satu goresan melengkung seperti gelombang' }
];

const hiragana_dakuten = [
    { char: 'が', romaji: 'ga' }, { char: 'ぎ', romaji: 'gi' }, { char: 'ぐ', romaji: 'gu' },
    { char: 'げ', romaji: 'ge' }, { char: 'ご', romaji: 'go' },
    { char: 'ざ', romaji: 'za' }, { char: 'じ', romaji: 'ji' }, { char: 'ず', romaji: 'zu' },
    { char: 'ぜ', romaji: 'ze' }, { char: 'ぞ', romaji: 'zo' },
    { char: 'だ', romaji: 'da' }, { char: 'ぢ', romaji: 'ji' }, { char: 'づ', romaji: 'zu' },
    { char: 'で', romaji: 'de' }, { char: 'ど', romaji: 'do' },
    { char: 'ば', romaji: 'ba' }, { char: 'び', romaji: 'bi' }, { char: 'ぶ', romaji: 'bu' },
    { char: 'べ', romaji: 'be' }, { char: 'ぼ', romaji: 'bo' }
];

const hiragana_handakuten = [
    { char: 'ぱ', romaji: 'pa' }, { char: 'ぴ', romaji: 'pi' }, { char: 'ぷ', romaji: 'pu' },
    { char: 'ぺ', romaji: 'pe' }, { char: 'ぽ', romaji: 'po' }
];

const hiragana_youon = [
    { char: 'きゃ', romaji: 'kya' }, { char: 'きゅ', romaji: 'kyu' }, { char: 'きょ', romaji: 'kyo' },
    { char: 'しゃ', romaji: 'sha' }, { char: 'しゅ', romaji: 'shu' }, { char: 'しょ', romaji: 'sho' },
    { char: 'ちゃ', romaji: 'cha' }, { char: 'ちゅ', romaji: 'chu' }, { char: 'ちょ', romaji: 'cho' },
    { char: 'にゃ', romaji: 'nya' }, { char: 'にゅ', romaji: 'nyu' }, { char: 'にょ', romaji: 'nyo' },
    { char: 'ひゃ', romaji: 'hya' }, { char: 'ひゅ', romaji: 'hyu' }, { char: 'ひょ', romaji: 'hyo' },
    { char: 'みゃ', romaji: 'mya' }, { char: 'みゅ', romaji: 'myu' }, { char: 'みょ', romaji: 'myo' },
    { char: 'りゃ', romaji: 'rya' }, { char: 'りゅ', romaji: 'ryu' }, { char: 'りょ', romaji: 'ryo' },
    { char: 'ぎゃ', romaji: 'gya' }, { char: 'ぎゅ', romaji: 'gyu' }, { char: 'ぎょ', romaji: 'gyo' },
    { char: 'じゃ', romaji: 'ja' }, { char: 'じゅ', romaji: 'ju' }, { char: 'じょ', romaji: 'jo' },
    { char: 'ぢゃ', romaji: 'ja' }, { char: 'ぢゅ', romaji: 'ju' }, { char: 'ぢょ', romaji: 'jo' },
    { char: 'びゃ', romaji: 'bya' }, { char: 'びゅ', romaji: 'byu' }, { char: 'びょ', romaji: 'byo' },
    { char: 'ぴゃ', romaji: 'pya' }, { char: 'ぴゅ', romaji: 'pyu' }, { char: 'ぴょ', romaji: 'pyo' }
];

const katakana_dasar = [
    { char: 'ア', romaji: 'a', strokes: 'Dua goresan diagonal dari atas' },
    { char: 'イ', romaji: 'i', strokes: 'Dua garis vertikal' },
    { char: 'ウ', romaji: 'u', strokes: 'Tiga goresan membentuk huruf' },
    { char: 'エ', romaji: 'e', strokes: 'Tiga garis horizontal' },
    { char: 'オ', romaji: 'o', strokes: 'Tiga goresan: horizontal, vertikal, diagonal' },
    { char: 'カ', romaji: 'ka', strokes: 'Dua goresan: horizontal, diagonal' },
    { char: 'キ', romaji: 'ki', strokes: 'Tiga garis horizontal, satu vertikal' },
    { char: 'ク', romaji: 'ku', strokes: 'Dua garis diagonal' },
    { char: 'ケ', romaji: 'ke', strokes: 'Tiga goresan membentuk sudut' },
    { char: 'コ', romaji: 'ko', strokes: 'Dua garis horizontal' },
    { char: 'サ', romaji: 'sa', strokes: 'Tiga goresan: horizontal, vertikal, diagonal' },
    { char: 'シ', romaji: 'shi', strokes: 'Tiga garis diagonal pendek' },
    { char: 'ス', romaji: 'su', strokes: 'Dua goresan diagonal' },
    { char: 'セ', romaji: 'se', strokes: 'Dua garis horizontal, satu diagonal' },
    { char: 'ソ', romaji: 'so', strokes: 'Dua garis diagonal pendek' },
    { char: 'タ', romaji: 'ta', strokes: 'Tiga goresan: horizontal, vertikal, diagonal' },
    { char: 'チ', romaji: 'chi', strokes: 'Tiga goresan membentuk huruf' },
    { char: 'ツ', romaji: 'tsu', strokes: 'Tiga garis diagonal vertikal' },
    { char: 'テ', romaji: 'te', strokes: 'Tiga goresan: horizontal, vertikal, horizontal' },
    { char: 'ト', romaji: 'to', strokes: 'Dua goresan: vertikal, diagonal' },
    { char: 'ナ', romaji: 'na', strokes: 'Dua goresan: horizontal diagonal, vertikal' },
    { char: 'ニ', romaji: 'ni', strokes: 'Dua garis horizontal' },
    { char: 'ヌ', romaji: 'nu', strokes: 'Dua goresan: diagonal, lengkungan' },
    { char: 'ネ', romaji: 'ne', strokes: 'Empat goresan membentuk huruf' },
    { char: 'ノ', romaji: 'no', strokes: 'Satu garis diagonal dari kiri atas ke kanan bawah' },
    { char: 'ハ', romaji: 'ha', strokes: 'Dua garis diagonal ke kanan' },
    { char: 'ヒ', romaji: 'hi', strokes: 'Dua goresan: vertikal, horizontal' },
    { char: 'フ', romaji: 'fu', strokes: 'Dua goresan: horizontal, diagonal' },
    { char: 'ヘ', romaji: 'he', strokes: 'Satu garis diagonal seperti topi' },
    { char: 'ホ', romaji: 'ho', strokes: 'Empat goresan membentuk kotak' },
    { char: 'マ', romaji: 'ma', strokes: 'Dua goresan: horizontal, vertikal diagonal' },
    { char: 'ミ', romaji: 'mi', strokes: 'Tiga garis horizontal pendek' },
    { char: 'ム', romaji: 'mu', strokes: 'Dua goresan diagonal membentuk V' },
    { char: 'メ', romaji: 'me', strokes: 'Dua garis diagonal menyilang' },
    { char: 'モ', romaji: 'mo', strokes: 'Tiga goresan: horizontal, vertikal, horizontal' },
    { char: 'ヤ', romaji: 'ya', strokes: 'Tiga goresan membentuk huruf' },
    { char: 'ユ', romaji: 'yu', strokes: 'Dua goresan: horizontal, lengkungan' },
    { char: 'ヨ', romaji: 'yo', strokes: 'Tiga garis horizontal' },
    { char: 'ラ', romaji: 'ra', strokes: 'Dua goresan: vertikal, horizontal' },
    { char: 'リ', romaji: 'ri', strokes: 'Dua garis vertikal' },
    { char: 'ル', romaji: 'ru', strokes: 'Dua goresan: vertikal, lengkungan' },
    { char: 'レ', romaji: 're', strokes: 'Dua goresan membentuk L' },
    { char: 'ロ', romaji: 'ro', strokes: 'Tiga goresan membentuk kotak' },
    { char: 'ワ', romaji: 'wa', strokes: 'Dua goresan: horizontal diagonal, vertikal' },
    { char: 'ヲ', romaji: 'wo', strokes: 'Tiga goresan membentuk huruf' },
    { char: 'ン', romaji: 'n', strokes: 'Satu garis diagonal dengan ekor' }
];

const katakana_dakuten = [
    { char: 'ガ', romaji: 'ga' }, { char: 'ギ', romaji: 'gi' }, { char: 'グ', romaji: 'gu' },
    { char: 'ゲ', romaji: 'ge' }, { char: 'ゴ', romaji: 'go' },
    { char: 'ザ', romaji: 'za' }, { char: 'ジ', romaji: 'ji' }, { char: 'ズ', romaji: 'zu' },
    { char: 'ゼ', romaji: 'ze' }, { char: 'ゾ', romaji: 'zo' },
    { char: 'ダ', romaji: 'da' }, { char: 'ヂ', romaji: 'ji' }, { char: 'ヅ', romaji: 'zu' },
    { char: 'デ', romaji: 'de' }, { char: 'ド', romaji: 'do' },
    { char: 'バ', romaji: 'ba' }, { char: 'ビ', romaji: 'bi' }, { char: 'ブ', romaji: 'bu' },
    { char: 'ベ', romaji: 'be' }, { char: 'ボ', romaji: 'bo' }
];

const katakana_handakuten = [
    { char: 'パ', romaji: 'pa' }, { char: 'ピ', romaji: 'pi' }, { char: 'プ', romaji: 'pu' },
    { char: 'ペ', romaji: 'pe' }, { char: 'ポ', romaji: 'po' }
];

const katakana_youon = [
    { char: 'キャ', romaji: 'kya' }, { char: 'キュ', romaji: 'kyu' }, { char: 'キョ', romaji: 'kyo' },
    { char: 'シャ', romaji: 'sha' }, { char: 'シュ', romaji: 'shu' }, { char: 'ショ', romaji: 'sho' },
    { char: 'チャ', romaji: 'cha' }, { char: 'チュ', romaji: 'chu' }, { char: 'チョ', romaji: 'cho' },
    { char: 'ニャ', romaji: 'nya' }, { char: 'ニュ', romaji: 'nyu' }, { char: 'ニョ', romaji: 'nyo' },
    { char: 'ヒャ', romaji: 'hya' }, { char: 'ヒュ', romaji: 'hyu' }, { char: 'ヒョ', romaji: 'hyo' },
    { char: 'ミャ', romaji: 'mya' }, { char: 'ミュ', romaji: 'myu' }, { char: 'ミョ', romaji: 'myo' },
    { char: 'リャ', romaji: 'rya' }, { char: 'リュ', romaji: 'ryu' }, { char: 'リョ', romaji: 'ryo' },
    { char: 'ギャ', romaji: 'gya' }, { char: 'ギュ', romaji: 'gyu' }, { char: 'ギョ', romaji: 'gyo' },
    { char: 'ジャ', romaji: 'ja' }, { char: 'ジュ', romaji: 'ju' }, { char: 'ジョ', romaji: 'jo' },
    { char: 'ヂャ', romaji: 'ja' }, { char: 'ヂュ', romaji: 'ju' }, { char: 'ヂョ', romaji: 'jo' },
    { char: 'ビャ', romaji: 'bya' }, { char: 'ビュ', romaji: 'byu' }, { char: 'ビョ', romaji: 'byo' },
    { char: 'ピャ', romaji: 'pya' }, { char: 'ピュ', romaji: 'pyu' }, { char: 'ピョ', romaji: 'pyo' }
];

const katakana_modern = [
    { char: 'ウィ', romaji: 'wi' }, { char: 'ウェ', romaji: 'we' }, { char: 'ウォ', romaji: 'wo' },
    { char: 'ヴァ', romaji: 'va' }, { char: 'ヴィ', romaji: 'vi' }, { char: 'ヴ', romaji: 'vu' },
    { char: 'ヴェ', romaji: 've' }, { char: 'ヴォ', romaji: 'vo' },
    { char: 'ファ', romaji: 'fa' }, { char: 'フィ', romaji: 'fi' }, { char: 'フェ', romaji: 'fe' },
    { char: 'フォ', romaji: 'fo' }, { char: 'フュ', romaji: 'fyu' },
    { char: 'ツァ', romaji: 'tsa' }, { char: 'ツィ', romaji: 'tsi' }, { char: 'ツェ', romaji: 'tse' },
    { char: 'ツォ', romaji: 'tso' },
    { char: 'ティ', romaji: 'ti' }, { char: 'トゥ', romaji: 'tu' },
    { char: 'ディ', romaji: 'di' }, { char: 'ドゥ', romaji: 'du' }, { char: 'デュ', romaji: 'dyu' },
    { char: 'チェ', romaji: 'che' }, { char: 'シェ', romaji: 'she' }, { char: 'ジェ', romaji: 'je' }
];

const kotoba = [
    { jp: 'おはようございます', romaji: 'ohayou gozaimasu', meaning: 'Selamat Pagi', category: 'greetings' },
    { jp: 'こんにちは', romaji: 'konnichiwa', meaning: 'Selamat Siang', category: 'greetings' },
    { jp: 'こんばんは', romaji: 'konbanwa', meaning: 'Selamat Malam', category: 'greetings' },
    { jp: 'おやすみなさい', romaji: 'oyasuminasai', meaning: 'Selamat Tidur', category: 'greetings' },
    { jp: 'いらっしゃいませ', romaji: 'irasshaimase', meaning: 'Selamat Datang', category: 'greetings' },
    { jp: 'さようなら', romaji: 'sayounara', meaning: 'Selamat Tinggal', category: 'greetings' },
    { jp: 'ただいま', romaji: 'tadaima', meaning: 'Aku Kembali (Rumah)', category: 'greetings' },
    { jp: 'おかえりなさい', romaji: 'okaerinasai', meaning: 'Selamat Datang Kembali', category: 'greetings' },
    { jp: 'いってきます', romaji: 'ittekimasu', meaning: 'Aku Pamit', category: 'greetings' },
    { jp: 'いってらっしゃい', romaji: 'itterasshai', meaning: 'Hati-hati', category: 'greetings' },
    { jp: 'またね', romaji: 'matane', meaning: 'Sampai Jumpa', category: 'greetings' },
    { jp: 'げんきです', romaji: 'genki desu', meaning: 'Kabar baik', category: 'greetings' },
    { jp: 'おめでとう', romaji: 'omedetou', meaning: 'Selamat', category: 'greetings' },
    { jp: 'おひさしぶりです', romaji: 'ohisashiburi desu', meaning: 'Sudah lama tidak bertemu', category: 'greetings' },
    { jp: 'おまたせしました', romaji: 'omatase shimashita', meaning: 'Maaf lama menunggu', category: 'greetings' },
    { jp: 'おねがいします', romaji: 'onegaishimasu', meaning: 'Mohon bantuannya', category: 'greetings' },
    { jp: 'すみません', romaji: 'sumimasen', meaning: 'Permisi / Maaf', category: 'greetings' },
    { jp: 'やめて', romaji: 'yamete', meaning: 'Berhenti', category: 'greetings' },
    { jp: 'すごい', romaji: 'sugoi', meaning: 'Hebat / Luar biasa', category: 'greetings' },
    { jp: 'かっこいい', romaji: 'kakkoii', meaning: 'Keren', category: 'greetings' },
    { jp: 'しつれいします', romaji: 'shitsureishimasu', meaning: 'Permisi', category: 'greetings' },
    { jp: 'ごめん', romaji: 'gomen', meaning: 'Maaf', category: 'greetings' },
    { jp: 'だいじょうぶ', romaji: 'daijoubu', meaning: 'Tidak apa apa', category: 'greetings' },
    { jp: 'ありがとう', romaji: 'arigatou', meaning: 'Terima kasih', category: 'greetings' },
    { jp: 'どういたしまして', romaji: 'douitashimashite', meaning: 'Sama-sama', category: 'greetings' },
    { jp: 'ちょっとまって', romaji: 'chotto matte', meaning: 'Tunggu sebentar', category: 'greetings' },
    { jp: 'おつかれさまです', romaji: 'otsukaresama desu', meaning: 'Terimakasih atas kerja kerasnya', category: 'greetings' },

    { jp: 'わたし', romaji: 'watashi', meaning: 'Saya', category: 'basic' },
    { jp: 'ぼく', romaji: 'boku', meaning: 'Saya (laki-laki)', category: 'basic' },
    { jp: 'かれら', romaji: 'karera', meaning: 'Mereka (laki-laki)', category: 'basic' },
    { jp: 'かのじょたち', romaji: 'kanojotachi', meaning: 'Mereka (perempuan)', category: 'basic' },
    { jp: 'きみ', romaji: 'kimi', meaning: 'Kamu', category: 'basic' },
    { jp: 'ひと', romaji: 'hito', meaning: 'Orang', category: 'basic' },
    { jp: 'がくせい', romaji: 'gakusei', meaning: 'Murid', category: 'basic' },
    { jp: 'せんせい', romaji: 'sensei', meaning: 'Guru', category: 'basic' },
    { jp: 'ともだち', romaji: 'tomodachi', meaning: 'Teman', category: 'basic' },
    { jp: 'しにゅう', romaji: 'shinyuu', meaning: 'Sahabat dekat', category: 'basic' },
    { jp: 'こいびと', romaji: 'koibito', meaning: 'Pasangan / kekasih', category: 'basic' },
    { jp: 'こども', romaji: 'kodomo', meaning: 'Anak-anak', category: 'basic' },
    { jp: 'なに', romaji: 'nani', meaning: 'Apa', category: 'basic' },
    { jp: 'はい', romaji: 'hai', meaning: 'Ya', category: 'basic' },
    { jp: 'でも', romaji: 'demo', meaning: 'Tapi', category: 'basic' },
    { jp: 'ほん', romaji: 'hon', meaning: 'Buku', category: 'basic' },
    { jp: 'じしょ', romaji: 'jisho', meaning: 'Kamus', category: 'basic' },

    { jp: 'ごはん', romaji: 'gohan', meaning: 'Nasi', category: 'food' },
    { jp: 'みず', romaji: 'mizu', meaning: 'Air', category: 'food' },
    { jp: 'おちゃ', romaji: 'ocha', meaning: 'Teh', category: 'food' },
    { jp: 'パン', romaji: 'pan', meaning: 'Roti', category: 'food' },
    { jp: 'ピザ', romaji: 'piza', meaning: 'Pizza', category: 'food' },
    { jp: 'コーヒー', romaji: 'koohii', meaning: 'Kopi', category: 'food' },
    { jp: 'バナナ', romaji: 'banana', meaning: 'Pisang', category: 'food' },
    { jp: 'ケーキ', romaji: 'keeki', meaning: 'Kue', category: 'food' },
    { jp: 'アイスクリーム', romaji: 'aisukuriimu', meaning: 'Es krim', category: 'food' },
    { jp: 'ジュース', romaji: 'juusu', meaning: 'Jus', category: 'food' },
    { jp: 'サンドイッチ', romaji: 'sandoicchi', meaning: 'Sandwich', category: 'food' },
    { jp: 'チョコレート', romaji: 'chokoreeto', meaning: 'Cokelat', category: 'food' },
    { jp: 'ハンバーガー', romaji: 'hanbaagaa', meaning: 'Hamburger', category: 'food' },
    { jp: 'パスタ', romaji: 'pasuta', meaning: 'Pasta', category: 'food' },
    { jp: 'サラダ', romaji: 'sarada', meaning: 'Salad', category: 'food' },

    { jp: 'かぞく', romaji: 'kazoku', meaning: 'Keluarga', category: 'family' },
    { jp: 'おとうさん', romaji: 'otousan', meaning: 'Ayah', category: 'family' },
    { jp: 'おかあさん', romaji: 'okaasan', meaning: 'Ibu', category: 'family' },
    { jp: 'おにいさん', romaji: 'oniisan', meaning: 'Kakak Laki-laki', category: 'family' },
    { jp: 'おねえさん', romaji: 'oneesan', meaning: 'Kakak Perempuan', category: 'family' },
    { jp: 'おじいさん', romaji: 'ojiisan', meaning: 'Kakek', category: 'family' },
    { jp: 'おばあさん', romaji: 'obaasan', meaning: 'Nenek', category: 'family' },
    { jp: 'おじさん', romaji: 'ojisan', meaning: 'Paman', category: 'family' },
    { jp: 'おばさん', romaji: 'obasan', meaning: 'Bibi', category: 'family' },

    { jp: 'いち', romaji: 'ichi', meaning: 'Satu', category: 'numbers' },
    { jp: 'に', romaji: 'ni', meaning: 'Dua', category: 'numbers' },
    { jp: 'さん', romaji: 'san', meaning: 'Tiga', category: 'numbers' },
    { jp: 'し', romaji: 'shi', meaning: 'Empat', category: 'numbers' },
    { jp: 'よん', romaji: 'yon', meaning: 'Empat', category: 'numbers' },
    { jp: 'ご', romaji: 'go', meaning: 'Lima', category: 'numbers' },
    { jp: 'ろく', romaji: 'roku', meaning: 'Enam', category: 'numbers' },
    { jp: 'しち', romaji: 'shichi', meaning: 'Tujuh', category: 'numbers' },
    { jp: 'なな', romaji: 'nana', meaning: 'Tujuh', category: 'numbers' },
    { jp: 'はち', romaji: 'hachi', meaning: 'Delapan', category: 'numbers' },
    { jp: 'きゅう', romaji: 'kyuu', meaning: 'Sembilan', category: 'numbers' },
    { jp: 'く', romaji: 'ku', meaning: 'Sembilan', category: 'numbers' },
    { jp: 'じゅう', romaji: 'juu', meaning: 'Sepuluh', category: 'numbers' },
    { jp: 'ひゃく', romaji: 'hyaku', meaning: 'Seratus', category: 'numbers' },
    { jp: 'せん', romaji: 'sen', meaning: 'Seribu', category: 'numbers' },
    { jp: 'まん', romaji: 'man', meaning: 'Sepuluh ribu', category: 'numbers' },

    { jp: 'きょう', romaji: 'kyou', meaning: 'Hari ini', category: 'time' },
    { jp: 'きのう', romaji: 'kinou', meaning: 'Kemarin', category: 'time' },
    { jp: 'あした', romaji: 'ashita', meaning: 'Besok', category: 'time' },
    { jp: 'あさって', romaji: 'asatte', meaning: 'Lusa', category: 'time' },
    { jp: 'あさ', romaji: 'asa', meaning: 'Pagi', category: 'time' },
    { jp: 'ひる', romaji: 'hiru', meaning: 'Siang', category: 'time' },
    { jp: 'よる', romaji: 'yoru', meaning: 'Malam', category: 'time' },
    { jp: 'つき', romaji: 'tsuki', meaning: 'Bulan', category: 'time' },
    { jp: 'とし', romaji: 'toshi', meaning: 'Tahun', category: 'time' },
    { jp: 'まいにち', romaji: 'mainichi', meaning: 'Setiap hari', category: 'time' },

    { jp: 'おいしい', romaji: 'oishii', meaning: 'Enak / Lezat', category: 'adjectives' },
    { jp: 'こわい', romaji: 'kowai', meaning: 'Seram / Menakutkan', category: 'adjectives' },
    { jp: 'たのしい', romaji: 'tanoshii', meaning: 'Seru / Menyenangkan', category: 'adjectives' },
    { jp: 'きらい', romaji: 'kirai', meaning: 'Benci', category: 'adjectives' },
    { jp: 'すき', romaji: 'suki', meaning: 'Suka', category: 'adjectives' },
    { jp: 'かなしい', romaji: 'kanashii', meaning: 'Sedih', category: 'adjectives' },
    { jp: 'ながい', romaji: 'nagai', meaning: 'Panjang', category: 'adjectives' },
    { jp: 'みじかい', romaji: 'mijikai', meaning: 'Pendek', category: 'adjectives' },
    { jp: 'あたらしい', romaji: 'atarashii', meaning: 'Baru', category: 'adjectives' },
    { jp: 'ふるい', romaji: 'furui', meaning: 'Lama', category: 'adjectives' },
    { jp: 'おおきい', romaji: 'ookii', meaning: 'Besar', category: 'adjectives' },
    { jp: 'ちいさい', romaji: 'chiisai', meaning: 'Kecil', category: 'adjectives' },
    { jp: 'たかい', romaji: 'takai', meaning: 'Tinggi / Mahal', category: 'adjectives' },
    { jp: 'やすい', romaji: 'yasui', meaning: 'Murah', category: 'adjectives' },
    { jp: 'かわいい', romaji: 'kawaii', meaning: 'Imut', category: 'adjectives' },
    { jp: 'きれい', romaji: 'kirei', meaning: 'Cantik / Bersih', category: 'adjectives' },
    { jp: 'しろい', romaji: 'shiroi', meaning: 'Putih', category: 'adjectives' },
    { jp: 'くろい', romaji: 'kuroi', meaning: 'Hitam', category: 'adjectives' },
    { jp: 'あかい', romaji: 'akai', meaning: 'Merah', category: 'adjectives' },
    { jp: 'あおい', romaji: 'aoi', meaning: 'Biru', category: 'adjectives' },

    { jp: 'おこる', romaji: 'okoru', meaning: 'Marah', category: 'verbs' },
    { jp: 'わらう', romaji: 'warau', meaning: 'Tertawa', category: 'verbs' },
    { jp: 'みる', romaji: 'miru', meaning: 'Melihat', category: 'verbs' },
    { jp: 'きく', romaji: 'kiku', meaning: 'Mendengar', category: 'verbs' },
    { jp: 'たべる', romaji: 'taberu', meaning: 'Makan', category: 'verbs' },
    { jp: 'のむ', romaji: 'nomu', meaning: 'Minum', category: 'verbs' },
    { jp: 'ねる', romaji: 'neru', meaning: 'Tidur', category: 'verbs' },
    { jp: 'いく', romaji: 'iku', meaning: 'Pergi', category: 'verbs' },
    { jp: 'くる', romaji: 'kuru', meaning: 'Datang', category: 'verbs' },
    { jp: 'かう', romaji: 'kau', meaning: 'Membeli', category: 'verbs' },
    { jp: 'よむ', romaji: 'yomu', meaning: 'Membaca', category: 'verbs' },
    { jp: 'かく', romaji: 'kaku', meaning: 'Menulis', category: 'verbs' },
    { jp: 'はなす', romaji: 'hanasu', meaning: 'Berbicara', category: 'verbs' },
    { jp: 'べんきょうする', romaji: 'benkyou suru', meaning: 'Belajar', category: 'verbs' },

    { jp: 'がっこう', romaji: 'gakkou', meaning: 'Sekolah', category: 'places' },
    { jp: 'まち', romaji: 'machi', meaning: 'Kota', category: 'places' },
    { jp: 'いなか', romaji: 'inaka', meaning: 'Desa / Kampung', category: 'places' },
    { jp: 'くに', romaji: 'kuni', meaning: 'Negara', category: 'places' },
    { jp: 'みせ', romaji: 'mise', meaning: 'Toko / Kedai', category: 'places' },
    { jp: 'レストラン', romaji: 'resutoran', meaning: 'Restoran', category: 'places' },
    { jp: 'ホテル', romaji: 'hoteru', meaning: 'Hotel', category: 'places' },
    { jp: 'えき', romaji: 'eki', meaning: 'Stasiun', category: 'places' },
    { jp: 'こうえん', romaji: 'kouen', meaning: 'Taman', category: 'places' },
    { jp: 'びょういん', romaji: 'byouin', meaning: 'Rumah Sakit', category: 'places' },
    { jp: 'スーパー', romaji: 'suupaa', meaning: 'Supermarket', category: 'places' },
    { jp: 'コンビニ', romaji: 'konbini', meaning: 'Minimarket', category: 'places' },
    { jp: 'としょかん', romaji: 'toshokan', meaning: 'Perpustakaan', category: 'places' },
    { jp: 'うち', romaji: 'uchi', meaning: 'Rumah', category: 'places' },
    { jp: 'へや', romaji: 'heya', meaning: 'Kamar', category: 'places' },

    { jp: 'はな', romaji: 'hana', meaning: 'Bunga', category: 'nature' },
    { jp: 'ひかり', romaji: 'hikari', meaning: 'Cahaya', category: 'nature' },
    { jp: 'そら', romaji: 'sora', meaning: 'Langit', category: 'nature' },
    { jp: 'ねこ', romaji: 'neko', meaning: 'Kucing', category: 'nature' },
    { jp: 'いぬ', romaji: 'inu', meaning: 'Anjing', category: 'nature' },
    { jp: 'うみ', romaji: 'umi', meaning: 'Laut', category: 'nature' },
    { jp: 'かわ', romaji: 'kawa', meaning: 'Sungai', category: 'nature' },
    { jp: 'やま', romaji: 'yama', meaning: 'Gunung', category: 'nature' },
    { jp: 'てんき', romaji: 'tenki', meaning: 'Cuaca', category: 'nature' },
    { jp: 'あめ', romaji: 'ame', meaning: 'Hujan', category: 'nature' },
    { jp: 'ゆき', romaji: 'yuki', meaning: 'Salju', category: 'nature' },
    { jp: 'かぜ', romaji: 'kaze', meaning: 'Angin', category: 'nature' },
    { jp: 'き', romaji: 'ki', meaning: 'Pohon', category: 'nature' },
    { jp: 'ほし', romaji: 'hoshi', meaning: 'Bintang', category: 'nature' },

    { jp: 'タクシー', romaji: 'takushii', meaning: 'Taksi', category: 'katakana' },
    { jp: 'サッカー', romaji: 'sakkaa', meaning: 'Sepak bola', category: 'katakana' },
    { jp: 'テレビ', romaji: 'terebi', meaning: 'Televisi', category: 'katakana' },
    { jp: 'ラジオ', romaji: 'rajio', meaning: 'Radio', category: 'katakana' },
    { jp: 'エアコン', romaji: 'eakon', meaning: 'AC', category: 'katakana' },
    { jp: 'インターネット', romaji: 'intaanetto', meaning: 'Internet', category: 'katakana' },
    { jp: 'コンピュータ', romaji: 'konpyuuta', meaning: 'Komputer', category: 'katakana' },
    { jp: 'スマートフォン', romaji: 'sumaatofoon', meaning: 'Smartphone', category: 'katakana' },
    { jp: 'カメラ', romaji: 'kamera', meaning: 'Kamera', category: 'katakana' },
    { jp: 'ノート', romaji: 'nooto', meaning: 'Buku catatan', category: 'katakana' },
    { jp: 'ペン', romaji: 'pen', meaning: 'Pulpen', category: 'katakana' },
    { jp: 'バス', romaji: 'basu', meaning: 'Bus', category: 'katakana' },
    { jp: 'カップ', romaji: 'kappu', meaning: 'Cangkir', category: 'katakana' },
    { jp: 'スプーン', romaji: 'supuun', meaning: 'Sendok', category: 'katakana' },
    { jp: 'フォーク', romaji: 'fooku', meaning: 'Garpu', category: 'katakana' },
    { jp: 'ナイフ', romaji: 'naifu', meaning: 'Pisau', category: 'katakana' },
    { jp: 'プレゼント', romaji: 'purezento', meaning: 'Hadiah', category: 'katakana' },
    { jp: 'パーティー', romaji: 'paatii', meaning: 'Pesta', category: 'katakana' },
    { jp: 'ゲーム', romaji: 'geemu', meaning: 'Game', category: 'katakana' },
    { jp: 'スポーツ', romaji: 'supootsu', meaning: 'Olahraga', category: 'katakana' },
    { jp: 'ミュージック', romaji: 'myuujikku', meaning: 'Musik', category: 'katakana' },
    { jp: 'アニメ', romaji: 'anime', meaning: 'Anime', category: 'katakana' },
    { jp: 'ドア', romaji: 'doa', meaning: 'Pintu', category: 'katakana' },
    { jp: 'ベッド', romaji: 'beddo', meaning: 'Tempat tidur', category: 'katakana' },
    { jp: 'テーブル', romaji: 'teeburu', meaning: 'Meja', category: 'katakana' },
    { jp: 'チェア', romaji: 'chea', meaning: 'Kursi', category: 'katakana' },
    { jp: 'バッグ', romaji: 'baggu', meaning: 'Tas', category: 'katakana' },
    { jp: 'シャツ', romaji: 'shatsu', meaning: 'Baju', category: 'katakana' },
    { jp: 'ズボン', romaji: 'zubon', meaning: 'Celana', category: 'katakana' },
    { jp: 'スカート', romaji: 'sukaato', meaning: 'Rok', category: 'katakana' },
    { jp: 'ブーツ', romaji: 'buutsu', meaning: 'Sepatu boot', category: 'katakana' },
    { jp: 'ソックス', romaji: 'sokkusu', meaning: 'Kaos kaki', category: 'katakana' }
];

const kanji = [
    { jp: '魚', romaji: 'sakana', meaning: 'Ikan', category: 'makanan' },
    { jp: '肉', romaji: 'niku', meaning: 'Daging', category: 'makanan' },
    { jp: '卵', romaji: 'tamago', meaning: 'Telur', category: 'makanan' },
    { jp: '水', romaji: 'mizu', meaning: 'Air', category: 'makanan' },
    { jp: '食べます', romaji: 'tabemasu', meaning: 'Makan', category: 'kata_kerja' },
    { jp: '飲みます', romaji: 'nomimasu', meaning: 'Minum', category: 'kata_kerja' },
    { jp: '新しい', romaji: 'atarashii', meaning: 'Baru', category: 'sifat' },
    { jp: '古い', romaji: 'furui', meaning: 'Lama / Tua', category: 'sifat' },
    { jp: '大きい', romaji: 'ookii', meaning: 'Besar', category: 'sifat' },
    { jp: '小さい', romaji: 'chiisai', meaning: 'Kecil', category: 'sifat' },
    { jp: '時', romaji: ['ji', 'toki'], meaning: 'Jam (waktu)', category: 'waktu' },
    { jp: '分', romaji: ['fun', 'pun'], meaning: 'Menit', category: 'waktu' },
    { jp: '半', romaji: 'han', meaning: 'Setengah', category: 'waktu' },
    { jp: '月曜日', romaji: 'getsuyoubi', meaning: 'Senin', category: 'waktu' },
    { jp: '火曜日', romaji: 'kayoubi', meaning: 'Selasa', category: 'waktu' },
    { jp: '水曜日', romaji: 'suiyoubi', meaning: 'Rabu', category: 'waktu' },
    { jp: '木曜日', romaji: 'mokuyoubi', meaning: 'Kamis', category: 'waktu' },
    { jp: '金曜日', romaji: 'kinyoubi', meaning: 'Jumat', category: 'waktu' },
    { jp: '土曜日', romaji: 'doyoubi', meaning: 'Sabtu', category: 'waktu' },
    { jp: '日曜日', romaji: 'nichiyoubi', meaning: 'Minggu', category: 'waktu' },
    { jp: '言います', romaji: 'iimasu', meaning: 'Mengatakan', category: 'kata_kerja' },
    { jp: '話します', romaji: 'hanashimasu', meaning: 'Berbicara', category: 'kata_kerja' },
    { jp: '読みます', romaji: 'yomimasu', meaning: 'Membaca', category: 'kata_kerja' },
    { jp: '見ます', romaji: 'mimasu', meaning: 'Melihat', category: 'kata_kerja' },
    { jp: '聞きます', romaji: 'kikimasu', meaning: 'Mendengar / Bertanya', category: 'kata_kerja' },
    { jp: '書きます', romaji: 'kakimasu', meaning: 'Menulis', category: 'kata_kerja' },
    { jp: '一', romaji: 'ichi', meaning: 'Satu', category: 'angka' },
    { jp: '二', romaji: 'ni', meaning: 'Dua', category: 'angka' },
    { jp: '三', romaji: 'san', meaning: 'Tiga', category: 'angka' },
    { jp: '四', romaji: ['yon', 'shi'], meaning: 'Empat', category: 'angka' },
    { jp: '五', romaji: 'go', meaning: 'Lima', category: 'angka' },
    { jp: '六', romaji: 'roku', meaning: 'Enam', category: 'angka' },
    { jp: '七', romaji: ['nana', 'shichi'], meaning: 'Tujuh', category: 'angka' },
    { jp: '八', romaji: 'hachi', meaning: 'Delapan', category: 'angka' },
    { jp: '九', romaji: ['kyuu', 'ku'], meaning: 'Sembilan', category: 'angka' },
    { jp: '十', romaji: ['juu', 'too'], meaning: 'Sepuluh', category: 'angka' },
    { jp: '年', romaji: ['nen', 'toshi'], meaning: 'Tahun', category: 'waktu' },
    { jp: '日', romaji: ['nichi', 'hi'], meaning: 'Hari / Tanggal', category: 'waktu' },
    { jp: '月', romaji: ['gatsu', 'tsuki'], meaning: 'Bulan', category: 'waktu' },
    { jp: '東', romaji: 'higashi', meaning: 'Timur', category: 'arah' },
    { jp: '西', romaji: 'nishi', meaning: 'Barat', category: 'arah' },
    { jp: '南', romaji: 'minami', meaning: 'Selatan', category: 'arah' },
    { jp: '北', romaji: 'kita', meaning: 'Utara', category: 'arah' },
    { jp: '口', romaji: 'kuchi', meaning: 'Mulut / Pintu', category: 'arah' },
    { jp: '東口', romaji: 'higashiguchi', meaning: 'Pintu keluar timur', category: 'arah' },
    { jp: '西口', romaji: 'nishiguchi', meaning: 'Pintu keluar barat', category: 'arah' },
    { jp: '南口', romaji: 'minamiguchi', meaning: 'Pintu keluar selatan', category: 'arah' },
    { jp: '北口', romaji: 'kitaguchi', meaning: 'Pintu keluar utara', category: 'arah' },
    { jp: 'お金', romaji: 'okane', meaning: 'Uang', category: 'uang' },
    { jp: '円', romaji: 'en', meaning: 'Yen', category: 'uang' },
    { jp: '百', romaji: 'hyaku', meaning: 'Seratus', category: 'angka' },
    { jp: '千', romaji: 'sen', meaning: 'Seribu', category: 'angka' },
    { jp: '万', romaji: 'man', meaning: 'Sepuluh ribu', category: 'angka' },
    { jp: '百円', romaji: 'hyakuen', meaning: '100 Yen', category: 'uang' },
    { jp: '千円', romaji: 'senen', meaning: '1000 Yen', category: 'uang' },
    { jp: '一万円', romaji: 'ichimanen', meaning: '10.000 Yen', category: 'uang' },
    { jp: '買います', romaji: 'kaimasu', meaning: 'Membeli', category: 'kata_kerja' },
    { jp: '買い物', romaji: 'kaimono', meaning: 'Belanja', category: 'kata_kerja' },
    { jp: '行きます', romaji: 'ikimasu', meaning: 'Pergi', category: 'kata_kerja' },
    { jp: '来ます', romaji: 'kimasu', meaning: 'Datang', category: 'kata_kerja' },
    { jp: '会います', romaji: 'aimasu', meaning: 'Bertemu', category: 'kata_kerja' },
    { jp: '休みます', romaji: 'yasumimasu', meaning: 'Istirahat / Libur', category: 'kata_kerja' },
    { jp: '日本', romaji: ['nihon', 'nippon'], meaning: 'Jepang', category: 'negara' },
    { jp: '東京', romaji: 'toukyou', meaning: 'Tokyo', category: 'negara' },
    { jp: '私', romaji: ['watashi', 'watakushi'], meaning: 'Saya', category: 'orang' },
    { jp: '父', romaji: 'chichi', meaning: 'Ayah (saya)', category: 'orang' },
    { jp: '母', romaji: 'haha', meaning: 'Ibu (saya)', category: 'orang' },
    { jp: '子供', romaji: 'kodomo', meaning: 'Anak', category: 'orang' },
    { jp: '男', romaji: 'otoko', meaning: 'Laki-laki', category: 'orang' },
    { jp: '女', romaji: 'onna', meaning: 'Perempuan', category: 'orang' },
    { jp: '人', romaji: ['hito', 'nin', 'jin'], meaning: 'Orang', category: 'orang' },
    { jp: 'お父さん', romaji: 'otousan', meaning: 'Ayah (orang lain)', category: 'orang' },
    { jp: 'お母さん', romaji: 'okaasan', meaning: 'Ibu (orang lain)', category: 'orang' },
    { jp: '国', romaji: 'kuni', meaning: 'Negara', category: 'negara' },
    { jp: '外国', romaji: 'gaikoku', meaning: 'Luar negeri', category: 'negara' },
    { jp: '何人', romaji: ['nanijin', 'nannin'], meaning: 'Orang mana (kebangsaan) / Berapa orang', category: 'negara' },
    { jp: '語', romaji: 'go', meaning: 'Bahasa (akhiran)', category: 'bahasa' },
    { jp: '日本語', romaji: 'nihongo', meaning: 'Bahasa Jepang', category: 'bahasa' },
    { jp: '英語', romaji: 'eigo', meaning: 'Bahasa Inggris', category: 'bahasa' },
    { jp: '中国語', romaji: 'chuugokugo', meaning: 'Bahasa Mandarin', category: 'bahasa' },
    { jp: '日本人', romaji: 'nihonjin', meaning: 'Orang Jepang', category: 'negara' },
    { jp: '何', romaji: ['nani', 'nan'], meaning: 'Apa', category: 'basic' },
    { jp: '好き', romaji: 'suki', meaning: 'Suka', category: 'sifat' },
    { jp: '本', romaji: 'hon', meaning: 'Buku', category: 'basic' },
    { jp: '読書', romaji: 'dokusho', meaning: 'Membaca buku', category: 'kata_kerja' },
    { jp: '春', romaji: 'haru', meaning: 'Musim semi', category: 'musim' },
    { jp: '秋', romaji: 'aki', meaning: 'Musim gugur', category: 'musim' },
    { jp: '夏', romaji: 'natsu', meaning: 'Musim panas', category: 'musim' },
    { jp: '冬', romaji: 'fuyu', meaning: 'Musim dingin', category: 'musim' },
    { jp: '今', romaji: 'ima', meaning: 'Sekarang', category: 'waktu' },
    { jp: '今日', romaji: 'kyou', meaning: 'Hari ini', category: 'waktu' },
    { jp: '花', romaji: 'hana', meaning: 'Bunga', category: 'alam' },
    { jp: '海', romaji: 'umi', meaning: 'Laut', category: 'alam' },
    { jp: '山', romaji: 'yama', meaning: 'Gunung', category: 'alam' },
    { jp: '川', romaji: 'kawa', meaning: 'Sungai', category: 'alam' },
    { jp: '雨', romaji: 'ame', meaning: 'Hujan', category: 'alam' },
    { jp: '雪', romaji: 'yuki', meaning: 'Salju', category: 'alam' },
    { jp: '天気', romaji: 'tenki', meaning: 'Cuaca', category: 'alam' },
    { jp: '晴れ', romaji: 'hare', meaning: 'Cerah', category: 'alam' },
    { jp: '雲', romaji: 'kumo', meaning: 'Awan', category: 'alam' }
];
